### ISSUE TITLE
最右边的√图标有回调事件吗

### ISSUE THREAD

**Issue by toastIsGood** [likaia/js-screen-shot#1]

**Comment by likaia** [comment]
没有，我把裁剪出来的数据放在本地存储里了

**Comment by likaia** [comment]
现在有回调事件了

**Comment by Snow233** [comment]
> 现在有回调事件了

使用canvas将video标签中的内容绘制到canvas容器中，在这一部能否提供一个钩子函数可以支持对canvas中的图像进行部分区域裁剪，负责页面整体下移，截取不到底部

**Comment by likaia** [comment]
> > 现在有回调事件了
> 
> 使用canvas将video标签中的内容绘制到canvas容器中，在这一部能否提供一个钩子函数可以支持对canvas中的图像进行部分区域裁剪，否则页面整体下移，截取不到底部

我直接把插件的截图容器暴露出来了，使用getCanvasController方法去获取，具体看文档。
