### ISSUE TITLE
不支持iframe元素

### ISSUE THREAD

**Issue by Snow233** [likaia/js-screen-shot#10]
页面存在iframe元素时无法选定区域截图

**Comment by likaia** [comment]
用webrtc模式呢？

**Comment by Snow233** [comment]
> 用webrtc模式呢？

是我的页面iframe层级问题导致的，已经解决了，有办法设置宽高比和初始宽高大小以及在裁剪时候如果不全屏的话页面会往下偏移，导致无法选择底部区域
