### ISSUE TITLE
【bug】工具栏在最上面时，点击某个工具出现选色和粗细会把工具栏顶出屏幕，不能取消和换工具

### ISSUE THREAD

**Issue by iced-lemon-tea** [likaia/js-screen-shot#104]
![image](https://user-images.githubusercontent.com/45138230/227557895-0e81f2f3-e0ea-4566-9e5a-ddb1f565acba.png)
![image](https://user-images.githubusercontent.com/45138230/227557957-1ce26a95-dc72-49c7-9231-65ac15e4f505.png)

**Comment by likaia** [comment]
已修复，将插件更新到最新版本即可
