### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by sz-phg** [likaia/js-screen-shot#105]
运行时报错
![a313df8e93af7932fe44b317b7ccd8d](https://user-images.githubusercontent.com/124052195/227921149-e11be193-e336-4330-bba6-27d822826a1e.png)

**Comment by likaia** [comment]
你这是用什么搭建的项目？

**Comment by kunger309** [comment]
我也是报错，vue2

**Comment by likaia** [comment]
> 运行时报错 ![a313df8e93af7932fe44b317b7ccd8d](https://user-images.githubusercontent.com/124052195/227921149-e11be193-e336-4330-bba6-27d822826a1e.png)

更新到1.8.9-rc.0版本试一下？

**Comment by likaia** [comment]
> 我也是报错，vue2

更新到1.8.9-rc.0试一下

**Comment by kunger309** [comment]
> 

好像不行，有新的报错
![image](https://user-images.githubusercontent.com/77869538/228417629-965fd8bb-ce5f-41c9-b5eb-a74a4a22f739.png)

**Comment by likaia** [comment]
> > 
> 
> 好像不行，有新的报错 ![image](https://user-images.githubusercontent.com/77869538/228417629-965fd8bb-ce5f-41c9-b5eb-a74a4a22f739.png)

定位到问题了，是因为打包后的代码没有转es5引发的。你更新到1.8.9-rc.1版本试试看。

**Comment by likaia** [comment]
> 运行时报错 ![a313df8e93af7932fe44b317b7ccd8d](https://user-images.githubusercontent.com/124052195/227921149-e11be193-e336-4330-bba6-27d822826a1e.png)

定位到问题了，是因为打包后的代码没有转es5引发的。你更新到1.8.9-rc.1版本试试看。

**Comment by likaia** [comment]
该问题已修复，将插件更新至1.9.0版本即可。
