### ISSUE TITLE
能否加一个设置，可以控制截图是否保存到剪贴板

### ISSUE THREAD

**Issue by Dead-Universe** [likaia/js-screen-shot#118]
### Version of js-screen-shot

1.9.3

### 你的想法是什么?

我目前的项目有个需求，截图之后进行OCR，我的想法是OCR之后把结果保存到剪贴板，在之前使用vue版插件时，出现了OCR结果先放入剪贴板，截图后放入的情况，使用了通用版之后测试了几次没有出现该问题，但还是希望有个属性可以控制以下，以防出现该BUG。

**Comment by likaia** [comment]
Hello @Dead-Universe. Your suggestion has been received, and you will be notified in the issue area after the evaluation is completed.
你好 @Dead-Universe，已收到你的建议，评估完成后将在issue区域通知你。

**Comment by likaia** [comment]
> 

可以的，我加一下

**Comment by likaia** [comment]
> 

可以的我加一下

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.3
> 
> ### 你的想法是什么?
> 我目前的项目有个需求，截图之后进行OCR，我的想法是OCR之后把结果保存到剪贴板，在之前使用vue版插件时，出现了OCR结果先放入剪贴板，截图后放入的情况，使用了通用版之后测试了几次没有出现该问题，但还是希望有个属性可以控制以下，以防出现该BUG。

加好了，更新到1.9.4版本即可，具体看文档
