### ISSUE TITLE
截图的时候，截的图和出来的base64里的内容大小不同

### ISSUE THREAD

**Issue by LUCIFER-ZHU** [likaia/js-screen-shot#12]
![image](https://user-images.githubusercontent.com/57311383/130420203-b011b0f0-3af5-49d4-9e39-c8257bc895a6.png)
比如我要截上图这么多，但是出来的却是
![image](https://user-images.githubusercontent.com/57311383/130420346-d40fdbc9-5575-43ac-81cc-339aa4fdda1f.png)
是我用的姿势不对么？

>       new ScreenShort({
>         enableWebRtc :false,
>         completeCallback : this.completeCallback,
>         closeCallback : this.closeCallback,
>         level : 99,
>         canvasWidth :0,
>         canvasHeight :0
>       });

**Comment by LUCIFER-ZHU** [comment]
![image](https://user-images.githubusercontent.com/57311383/130541360-521bee2e-ba59-4797-852c-3dcfd4c41c70.png)
和拉的姿势有关，从右下往左上拉区域大小计算有误

**Comment by likaia** [comment]
😂 这几天太忙了，没看GitHub。可以加你个微信吗？

**Comment by LUCIFER-ZHU** [comment]
可以，微信号zhujiamin223

**Comment by likaia** [comment]
OK
