### ISSUE TITLE
使用 WebRTC 截图，最下方缺少一块

### ISSUE THREAD

**Issue by Curacao-lb** [likaia/js-screen-shot#120]
### Version of js-screen-shot

1.9.7

### Operating system and its version

Windows

### Browser and its version

112.0.5615.138

### What happened?

推测：点击选择分享后，地址栏下方会弹出“停止共享”的类似字样
下面是我截取全屏的图片，用图片查看器查看缺少一部分内容
![image](https://github.com/likaia/js-screen-shot/assets/70992044/54e4b054-37dc-45d2-bee3-c666e091afd9)
![image](https://github.com/likaia/js-screen-shot/assets/70992044/3fff6717-437d-4fc9-a736-56c28fffa6c0)
![image](https://github.com/likaia/js-screen-shot/assets/70992044/c7e3bc65-4c4f-49d4-aedf-f75dcaba2a53)

### 报错信息

```shell
无报错信息
```

**Comment by likaia** [comment]
Hello @Curacao-lb. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @Curacao-lb，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.7
> 
> ### Operating system and its version
> Windows
> 
> ### Browser and its version
> 112.0.5615.138
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> 推测：点击选择分享后，地址栏下方会弹出“停止共享”的类似字样 下面是我截取全屏的图片，用图片查看器查看缺少一部分内容 ![image](https://user-images.githubusercontent.com/70992044/239152203-54e4b054-37dc-45d2-bee3-c666e091afd9.png) ![image](https://user-images.githubusercontent.com/70992044/239152610-3fff6717-437d-4fc9-a736-56c28fffa6c0.png) ![image](https://user-images.githubusercontent.com/70992044/239152728-c7e3bc65-4c4f-49d4-aedf-f75dcaba2a53.png)
> 
> ### 报错信息
> ```shell
> 无报错信息
> ```

新版本浏览器的bug，可以通过参数来修复，你传入wrcWindowMode参数，并将其值设为true

**Comment by Curacao-lb** [comment]
> wrcWindowMode

感谢，已解决
