### ISSUE TITLE
使用html2canvas模式截取页面中video标签时，video标签消失

### ISSUE THREAD

**Issue by C1rq** [likaia/js-screen-shot#123]
### Version of js-screen-shot

"js-web-screen-shot": "^1.9.7-rc.1"

### Operating system and its version

MacOS

### What happened?

 const screenShotClick = () => {
    const video_: any = document!.getElementById('_volum')
    console.dir(video_)
    video_.pause()
    const screenShotHandler = new ScreenShort({
      enableWebRtc: false, //是否显示选项框
      level: 99, //层级级别
      toolPosition: 'right',
      wrcWindowMode: true,
      loadCrossImg: true,
      maskColor: { r: 255, g: 255, b: 255, a: 0.5 },
      proxyUrl: '127.0.0.1:9099',
      completeCallback: callback,
      closeCallback: closeFn,
      hiddenToolIco: {
        save: true,
      },
    })
  }
![截屏2023-06-06 09 30 23](https://github.com/likaia/js-screen-shot/assets/78521850/99d9efe9-b8dc-49cd-8907-e0e1509c0c37)
![截屏2023-06-06 09 33 34](https://github.com/likaia/js-screen-shot/assets/78521850/e79a04e8-e3e2-45a7-9c87-91abedd0b201)
![截屏2023-06-06 09 34 16](https://github.com/likaia/js-screen-shot/assets/78521850/dfabbbf4-e78c-46f2-8942-4efa80c913b3)
出现蒙层的时候，video还没没有消失，画框的时候video就消失了

2.使用webrtc截图video没有消失，但是会弹窗确认，交互不好，设置了wrcWindowMode、enableWebRtc，还是弹分享提示

大佬帮忙看看

**Comment by likaia** [comment]
Hello @C1rq. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @C1rq，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> "js-web-screen-shot": "^1.9.7-rc.1"
> 
> ### Operating system and its version
> MacOS
> 
> ### Browser and its version
> _No response_
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> const screenShotClick = () => { const video_: any = document!.getElementById('_volum') console.dir(video_) video_.pause() const screenShotHandler = new ScreenShort({ enableWebRtc: false, //是否显示选项框 level: 99, //层级级别 toolPosition: 'right', wrcWindowMode: true, loadCrossImg: true, maskColor: { r: 255, g: 255, b: 255, a: 0.5 }, proxyUrl: '127.0.0.1:9099', completeCallback: callback, closeCallback: closeFn, hiddenToolIco: { save: true, }, }) } ![截屏2023-06-06 09 30 23](https://user-images.githubusercontent.com/78521850/243520756-99d9efe9-b8dc-49cd-8907-e0e1509c0c37.png) ![截屏2023-06-06 09 33 34](https://user-images.githubusercontent.com/78521850/243520907-e79a04e8-e3e2-45a7-9c87-91abedd0b201.png) ![截屏2023-06-06 09 34 16](https://user-images.githubusercontent.com/78521850/243520991-dfabbbf4-e78c-46f2-8942-4efa80c913b3.png) 出现蒙层的时候，video还没没有消失，画框的时候video就消失了
> 
> 2.使用webrtc截图video没有消失，但是会弹窗确认，交互不好，设置了wrcWindowMode、enableWebRtc，还是弹分享提示
> 
> 大佬帮忙看看
> 
> ### 报错信息
> _No response_

html2canvas模式不完美的，他截取不了视频。webrtc模式可以截取视频但是会有弹窗出来，这个没办法避免的
