### ISSUE TITLE
electron clickCutFullScreen:true不起作用

### ISSUE THREAD

**Issue by xjhwfe** [likaia/js-screen-shot#125]
### Version of js-screen-shot

1.9.7-rc.1

### What happened?

electron clickCutFullScreen:true不起作用

**Comment by likaia** [comment]
Hello @xjhwfe. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @xjhwfe，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.7-rc.1
> 
> ### Operating system and its version
> _No response_
> 
> ### Browser and its version
> _No response_
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> electron clickCutFullScreen:true不起作用
> 
> ### 报错信息
> _No response_

我记得我有修复，你更到最新版本看看
