### ISSUE TITLE
electron截屏开始鼠标按下时，客户端会被缩小。

### ISSUE THREAD

**Issue by xjhwfe** [likaia/js-screen-shot#126]
### Version of js-screen-shot

1.9.7-rc.1

### Browser and its version

electron13.3.0

### What happened?

图一原生界面，图2按下左键截屏后electron会有缩放。
![iwEcAqNwbmcDAQTRAe8F0QGeBrAmDsYyxehYFwR1ryc9AN8AB9IHuMTjCAAJomltCgAL0Sqq png_620x10000q90](https://github.com/likaia/js-screen-shot/assets/33824559/698f6151-945d-4ef3-a4ee-2e6aeb75763a)
![ce8d9a748d28c01042e33f2518b9da9e](https://github.com/likaia/js-screen-shot/assets/33824559/0a5027ce-d3db-43b1-93f2-97a429269f30)
截屏时中间会有个十字图标
![22807cbcb47d598b2b2806874126523f](https://github.com/likaia/js-screen-shot/assets/33824559/a7196d17-71df-48ca-be73-540136a72800)

**Comment by likaia** [comment]
Hello @xjhwfe. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @xjhwfe，已收到你反馈的问题，问题解决后将在issue区域通知你。
