### ISSUE TITLE
enableWebRtc 为false，截图界面存在视频的情况下，视频是黑色的，有办法解决一下嘛

### ISSUE THREAD

**Issue by linqiaoLiang** [likaia/js-screen-shot#127]
### Version of js-screen-shot

1.9.7-rc.2

### Operating system and its version

Windows

**Comment by likaia** [comment]
Hello @linqiaoLiang. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @linqiaoLiang，已收到你反馈的问题，问题解决后将在issue区域通知你。
