### ISSUE TITLE
能加一个方法，设置画布的颜色吗，现在都是蓝色，想换一种主题色

### ISSUE THREAD

**Issue by cjy816618** [likaia/js-screen-shot#128]
### Version of js-screen-shot

1.8.3

### 你的想法是什么?

![image](https://github.com/likaia/js-screen-shot/assets/47617771/d0069216-b25f-451b-a3d9-afc3c685ae2c)

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.8.3
> 
> ### 你的想法是什么?
> ![image](https://user-images.githubusercontent.com/47617771/246062456-d0069216-b25f-451b-a3d9-afc3c685ae2c.png)

加好了，将插件更到最新版本。

参数名字是cutBoxBdColor，具体使用方法看文档

**Comment by cjy816618** [comment]
> 

![image](https://github.com/likaia/js-screen-shot/assets/47617771/014ff009-5340-43bd-b470-cbb2dc749db7)

**Comment by likaia** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/47617771/247524630-014ff009-5340-43bd-b470-cbb2dc749db7.png)

😂大意了，改了
