### ISSUE TITLE
为什么截图内容是空白呢？

### ISSUE THREAD

**Issue by armin926** [likaia/js-screen-shot#129]
### Version of js-screen-shot

1.9.7-rc.2

### Operating system and its version

Windows

### Browser and its version

谷歌114.0.5735.134

### What happened?

![Snipaste_2023-06-26_13-37-37](https://github.com/likaia/js-screen-shot/assets/64004874/d3ec4d4e-e12e-4d93-aed4-81e47be080cc)
![Snipaste_2023-06-26_13-38-27](https://github.com/likaia/js-screen-shot/assets/64004874/ec4bee60-e169-49de-b39f-5dc9ea3d08f3)

**Comment by likaia** [comment]
Hello @armin926. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @armin926，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by armin926** [comment]
还有视频是不是没办法截取呢

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.7-rc.2
> 
> ### Operating system and its version
> Windows
> 
> ### Browser and its version
> 谷歌114.0.5735.134
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> ![Snipaste_2023-06-26_13-37-37](https://user-images.githubusercontent.com/64004874/248674478-d3ec4d4e-e12e-4d93-aed4-81e47be080cc.png) ![Snipaste_2023-06-26_13-38-27](https://user-images.githubusercontent.com/64004874/248674493-ec4bee60-e169-49de-b39f-5dc9ea3d08f3.png)
> 
> ### 报错信息
> _No response_

换webrtc模式

**Comment by likaia** [comment]
> ![Snipaste_2023-06-26_15-35-34](https://user-images.githubusercontent.com/64004874/248717980-78768b48-8302-4832-8e24-506623fa4754.png) ![Snipaste_2023-06-26_15-35-45](https://user-images.githubusercontent.com/64004874/248717993-2d7b6e7d-c69e-46b0-bbe9-3dcac76e7fbb.png) 是不是没法截视频

可以截取视频

**Comment by armin926** [comment]
但是我这里点截图的时候视频就空了，请问怎么设置呢

**Comment by likaia** [comment]
> 但是我这里点截图的时候视频就空了，请问怎么设置呢

因为你用的是h2c模式，你换webrtc就好了

**Comment by armin926** [comment]
哦好的，谢谢

**Comment by koalaink** [comment]
@likaia 我使用webrtc模式截图也会出现截出来的图片空白的问题，会是什么原因？有时候是好的，目前没找到稳定复现的路径
