### ISSUE TITLE
noScroll开启后，底部工具栏显示在当前截图区域下方，被遮挡

### ISSUE THREAD

**Issue by shiyunfei666** [likaia/js-screen-shot#131]
### Version of js-screen-shot

1.8.8

### Operating system and its version

Windows

### Browser and its version

chrome

**Comment by likaia** [comment]
Hello @shiyunfei666. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @shiyunfei666，已收到你反馈的问题，问题解决后将在issue区域通知你。
