### ISSUE TITLE
div 内部有滚动条如何滚动截屏？

### ISSUE THREAD

**Issue by wangshuai0** [likaia/js-screen-shot#132]
### 问题描述

页面没有滚动条，但是页面内部有个div有滚动条如何做到鼠标滚动截屏？

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> _No response_
> 
> ### 问题描述
> 页面没有滚动条，但是页面内部有个div有滚动条如何做到鼠标滚动截屏？

这个做不到
