### ISSUE TITLE
types 错误

### ISSUE THREAD

**Issue by 0jinxing** [likaia/js-screen-shot#133]
### Version of js-screen-shot

1.9.8-rc.3

### Operating system and its version

MacOS

### Browser and its version

无

### Sandbox to reproduce

无

### What happened?

![截屏2023-08-17 下午4 58 35](https://github.com/likaia/js-screen-shot/assets/32119282/efee2278-ac7e-4739-9c78-22b34f3ae9ce)

.npmignore 是不是 忽略了 tsconfig
```ts
import { screenShotType } from "@/lib/type/ComponentType";
```
这个 alias 找不到

### 报错信息

```shell
类型错误
```

**Comment by likaia** [comment]
Hello @0jinxing. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @0jinxing，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.8-rc.3
> 
> ### Operating system and its version
> MacOS
> 
> ### Browser and its version
> 无
> 
> ### Sandbox to reproduce
> 无
> 
> ### What happened?
> ![截屏2023-08-17 下午4 58 35](https://user-images.githubusercontent.com/32119282/261255998-efee2278-ac7e-4739-9c78-22b34f3ae9ce.png)
> 
> .npmignore 是不是 忽略了 tsconfig
> 
> ```ts
> import { screenShotType } from "@/lib/type/ComponentType";
> ```
> 
> 这个 alias 找不到
> 
> ### 报错信息
> ```shell
> 类型错误
> ```

这个问题修复了，你更新到1.9.9版本即可
