### ISSUE TITLE
尊敬的开发者您好，假如我仅使用图片编辑的工具栏，而不使用截图，将如何使用该插件，谢谢

### ISSUE THREAD

**Issue by havocera** [likaia/js-screen-shot#134]
### 你的想法是什么?

尊敬的开发者您好，假如我仅使用图片编辑的工具栏，而不使用截图，将如何使用该插件，谢谢

**Comment by likaia** [comment]
Hello @havocera. Your suggestion has been received, and you will be notified in the issue area after the evaluation is completed.
你好 @havocera，已收到你的建议，评估完成后将在issue区域通知你。
