### ISSUE TITLE
浏览器使用手机模式调试时，鼠标点击无法触发截图，只能弹起浮层，无法触发截图框

### ISSUE THREAD

**Issue by haiqihub** [likaia/js-screen-shot#135]
### Version of js-screen-shot

   "js-web-screen-shot": "^1.9.8-rc.3",

### 问题描述

需要的场景是，在浏览器截图h5调试的页面，但是这种触发不了鼠标点击事件

**Comment by likaia** [comment]
这个问题修复了，更新到1.9.9版本。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> "js-web-screen-shot": "^1.9.8-rc.3",
> 
> ### 问题描述
> 需要的场景是，在浏览器截图h5调试的页面，但是这种触发不了鼠标点击事件

我对触屏设备做了兼容处理，如果你是pc端的触屏设备可以支持webrtc模式，如果是移动端那么就只能使用html2canvas模式。
