### ISSUE TITLE
type screenShotType中的customRightClickEvent为什么是必填项

### ISSUE THREAD

**Issue by DoAutumn** [likaia/js-screen-shot#136]
### Version of js-screen-shot

1.9.9-rc.1

### What happened?

个人认为没有必要是必填项，如果不设置，语法校验会报错

**Comment by likaia** [comment]
Hello @DoAutumn. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @DoAutumn，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.9-rc.1
> 
> ### What happened?
> 个人认为没有必要是必填项，如果不设置，语法校验会报错

😂之前写的时候，搞错了，这里不是必填，我改下。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.9-rc.1
> 
> ### What happened?
> 个人认为没有必要是必填项，如果不设置，语法校验会报错

修复了，更到1.9.9-rc.2版本即可

**Comment by DoAutumn** [comment]
> > ### Version of js-screen-shot
> > 1.9.9-rc.1
> > ### What happened?
> > 个人认为没有必要是必填项，如果不设置，语法校验会报错
> 
> 修复了，更到1.9.9-rc.2版本即可

收到
