### ISSUE TITLE
关于firefox的错误提示

### ISSUE THREAD

**Issue by kure2** [likaia/js-screen-shot#138]
### Version of js-screen-shot

1.9.9 rc3

### 问题描述

firefox windows桌面版 118.0.1 (64 位）(latest)

使用方式：script标签引入

实例化组件完成后，使用框选工具时抛出异常：
![image](https://github.com/likaia/js-screen-shot/assets/32186515/1252dea1-fcf5-44d6-b262-6efcd5d572bf)

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.9 rc3
> 
> ### 问题描述
> firefox windows桌面版 118.0.1 (64 位）(latest)
> 
> 使用方式：script标签引入
> 
> 实例化组件完成后，使用框选工具时抛出异常： ![image](https://user-images.githubusercontent.com/32186515/273845475-1252dea1-fcf5-44d6-b262-6efcd5d572bf.png)

感谢反馈，我今晚处理下。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.9 rc3
> 
> ### 问题描述
> firefox windows桌面版 118.0.1 (64 位）(latest)
> 
> 使用方式：script标签引入
> 
> 实例化组件完成后，使用框选工具时抛出异常： ![image](https://user-images.githubusercontent.com/32186515/273845475-1252dea1-fcf5-44d6-b262-6efcd5d572bf.png)

修复了
