### ISSUE TITLE
在leaflet中，绘制截图区域的时候，蒙层上会出现要截图的元素内容

### ISSUE THREAD

**Issue by mmmmasdasd** [likaia/js-screen-shot#140]
### Version of js-screen-shot

1.9,9-rc.5

### Operating system and its version

MacOS

### Browser and its version

118.0.5993.88（正式版本） (x86_64)

### What happened?

![image](https://github.com/likaia/js-screen-shot/assets/47859908/84cc51cd-bac8-460d-b9a9-f442c5b46135)

**Comment by likaia** [comment]
Hello @mmmmasdasd. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @mmmmasdasd，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9,9-rc.5
> 
> ### Operating system and its version
> MacOS
> 
> ### Browser and its version
> 118.0.5993.88（正式版本） (x86_64)
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> ![image](https://user-images.githubusercontent.com/47859908/277904481-84cc51cd-bac8-460d-b9a9-f442c5b46135.png)
> 
> ### 报错信息
> _No response_

这个是因为你的截图内容小于你的容器了，没有铺满容器造成的。
