### ISSUE TITLE
马赛克涂鸦会被清除

### ISSUE THREAD

**Issue by LingLingShangJiangJun** [likaia/js-screen-shot#142]
### Version of js-screen-shot

1.9.9-rc.7

### Operating system and its version

Windows

### Browser and its version

Chrome 120.0.6099.110（正式版本） （64 位）

### What happened?

如果先在截图中画一个箭头A，然后在涂鸦马赛克M，此时再画一个箭头B。那么箭头A之后和箭头B之前涂鸦的马赛克M会被清掉。经测试箭头A之前的涂鸦的马赛克不会受影响。

**Comment by likaia** [comment]
Hello @LingLingShangJiangJun. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @LingLingShangJiangJun，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.9-rc.7
> 
> ### Operating system and its version
> Windows
> 
> ### Browser and its version
> Chrome 120.0.6099.110（正式版本） （64 位）
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> 如果先在截图中画一个箭头A，然后在涂鸦马赛克M，此时再画一个箭头B。那么箭头A之后和箭头B之前涂鸦的马赛克M会被清掉。经测试箭头A之前的涂鸦的马赛克不会受影响。
> 
> ### 报错信息
> _No response_

这个问题已修复，更到最新版本即可。
