### ISSUE TITLE
截图时svg图片不显示

### ISSUE THREAD

**Issue by DMSteins** [likaia/js-screen-shot#143]
### Version of js-screen-shot

1.9.9-rc.9

### Operating system and its version

MacOS

### Browser and its version

120.0.6099.199

### What happened?

前后对比，原本的svg在进入截图模式后消失了
![WX20240111-162739@2x](https://github.com/likaia/js-screen-shot/assets/13925194/45ce519d-b9fa-4e29-841c-74194a805ac0)
![1704961673342](https://github.com/likaia/js-screen-shot/assets/13925194/598a4887-a2c3-4836-a6be-ed586c5c54f9)

**Comment by likaia** [comment]
Hello @DMSteins. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @DMSteins，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.9-rc.9
> 
> ### Operating system and its version
> MacOS
> 
> ### Browser and its version
> 120.0.6099.199
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> 前后对比，原本的svg在进入截图模式后消失了 ![WX20240111-162739@2x](https://private-user-images.githubusercontent.com/13925194/295844634-45ce519d-b9fa-4e29-841c-74194a805ac0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzQ5ODAsIm5iZiI6MTcwNzczNDY4MCwicGF0aCI6Ii8xMzkyNTE5NC8yOTU4NDQ2MzQtNDVjZTUxOWQtYjlmYS00ZTI5LTg0MWMtNzQxOTRhODA1YWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEwNDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNzI1MDdlMWM3YzZjYjEzODg1NjM0MGJkM2MyNWU0ODMyNzdhZDMxMWUwMDgwNjljZDEwYTk0ODUwOWM4MjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zcdo_C7MJNM27TsOJvo5FHm69IaHr8nWHJAG_iyd828) ![1704961673342](https://private-user-images.githubusercontent.com/13925194/295844701-598a4887-a2c3-4836-a6be-ed586c5c54f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzQ5ODAsIm5iZiI6MTcwNzczNDY4MCwicGF0aCI6Ii8xMzkyNTE5NC8yOTU4NDQ3MDEtNTk4YTQ4ODctYTJjMy00ODM2LWE2YmUtZWQ1ODZjNWM1NGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEwNDQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwZGI5YmNhNmYxN2E1MDQ5YmUzZTFhM2Y2NDJlOTIyZjM4YjM4ZjRhMjIzN2E3M2E3NjIyNDk3YmFlOTJmNGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zWwgRUetsc5O4klV7r7aMdXPmhpOo7cWZ86HGaUK8f4)
> 
> ### 报错信息
> _No response_

html2canvas模式对svg的支持不友好
