### ISSUE TITLE
从1.9.8-rc.2升级到1.9.9之后，由于completeCallback返回值变化导致框选后点击确认按钮(√)报错

### ISSUE THREAD

**Issue by TY-LIU** [likaia/js-screen-shot#145]
### Version of js-screen-shot

1.9.9

### Operating system and its version

Windows

### What happened?

在1.9.8-rc.2版本的时候`completeCallback`回调函数返回值就是一个`base64`字符串，在升级之后，这个方法返回值变成了`object`，导致之前直接用`返回值.split(';base64,');`报没有split这个方法的错误，截图失败。
![image](https://github.com/likaia/js-screen-shot/assets/29595097/21d4c623-ff7f-41ed-8f19-2ab8862daba0)

### 建议声明文件里面加入接口提示
改前
![image](https://github.com/likaia/js-screen-shot/assets/29595097/853d6531-32ed-462b-b71d-3522aa88ee82)
改后
![image](https://github.com/likaia/js-screen-shot/assets/29595097/9fe35ef6-a0e2-4eca-a37f-f460a5b1d7ba)

**Comment by likaia** [comment]
Hello @TY-LIU. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @TY-LIU，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.9
> 
> ### Operating system and its version
> Windows
> 
> ### Browser and its version
> _No response_
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> 在1.9.8-rc.2版本的时候`completeCallback`回调函数返回值就是一个`base64`字符串，在升级之后，这个方法返回值变成了`object`，导致之前直接用`返回值.split(';base64,');`报没有split这个方法的错误，截图失败。 ![image](https://private-user-images.githubusercontent.com/29595097/296718988-21d4c623-ff7f-41ed-8f19-2ab8862daba0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTQ4MTcsIm5iZiI6MTcwNTMxNDUxNywicGF0aCI6Ii8yOTU5NTA5Ny8yOTY3MTg5ODgtMjFkNGM2MjMtZmY3Zi00MWVkLThmMTktMmFiODg2MmRhYmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEwMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExZGIxOTNkYzFjYWU1MWI0M2JiZWU2ZjliZDA2NTY3ZDk4MmEzN2Y5ZWRmYmRmYTY4MjhiZmQzODZkOGQ1ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2fzVgZmkgHwCB80OshV2Go25KqyTYFcH2DvmBgu03Qw)
> 
> ### 请在升级记录里面加入破坏式更新说明。
> ### 建议声明文件里面加入接口提示
> 改前 ![image](https://private-user-images.githubusercontent.com/29595097/296718617-853d6531-32ed-462b-b71d-3522aa88ee82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTQ4MTcsIm5iZiI6MTcwNTMxNDUxNywicGF0aCI6Ii8yOTU5NTA5Ny8yOTY3MTg2MTctODUzZDY1MzEtMzJlZC00NjJiLWI3MWQtMzUyMmFhODhlZTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEwMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MmUwMjM4YTliNWQwYTljNzRjZWUxODY5YzMxZDI4ZDZiODc3OGM2YTE3YTc1MjBiNzJjZGMxZjM5ODdhOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GV2-DiPHHs-DCVFBAMmJ9c5nTeGEJq6EHA53xqdg5bY) 改后 ![image](https://private-user-images.githubusercontent.com/29595097/296721175-9fe35ef6-a0e2-4eca-a37f-f460a5b1d7ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMTQ4MTcsIm5iZiI6MTcwNTMxNDUxNywicGF0aCI6Ii8yOTU5NTA5Ny8yOTY3MjExNzUtOWZlMzVlZjYtYTBlMi00ZWNhLWEzN2YtZjQ2MGE1YjFkN2JhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEwMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NjczNzMzMGMwYmY0YjE3ZWZlNjUyNmJkZjU1ZWM4ODBjOWFkODk5MjRlNWI4MDJjMzdlN2Y0YjdkNjdiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pPMQqDMvmURjxQfjr4nvNVoyC1LhbF2wBMhgv6PzX0A)
> 
> ### 报错信息
> _No response_

抱歉，我没考虑周到，我在日志里加一下，后面发版时我注意下。
