### ISSUE TITLE
使用imgSrc参数传入图片显示有不正确

### ISSUE THREAD

**Issue by miludedeng** [likaia/js-screen-shot#147]
### Version of js-screen-shot

1.9.9-rc.10

### Operating system and its version

MacOS, Windows

### Browser and its version

Nwjs

### What happened?

<img width="1722" alt="image" src="https://github.com/likaia/js-screen-shot/assets/4954870/75630f8e-518a-4cb2-9c3f-c565c827d4a9">
这个问题应该和高分辨率屏幕的缩放有关，在1080p分辨率下没有设置缩放的显示器下不会有这个问题。

**Comment by likaia** [comment]
Hello @miludedeng. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @miludedeng，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
修复了。更到1.9.9-rc.11
