### ISSUE TITLE
imgSrc属性绑定base64后，图片不能撑满canvas画板

### ISSUE THREAD

**Issue by jinsongen** [likaia/js-screen-shot#149]
### Version of js-screen-shot

1.9.9-rc.9

### What happened?

![1400677331-0000002111_test_t1-DOo3htTqkE3F339Pd3enGfGxVvNDIATh](https://github.com/likaia/js-screen-shot/assets/28554094/d9ecd969-1ec2-4a92-9ad0-a0b0bb244870)

**Comment by likaia** [comment]
Hello @jinsongen. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @jinsongen，已收到你反馈的问题，问题解决后将在issue区域通知你。
