### ISSUE TITLE
现在还有维护吗

### ISSUE THREAD

**Issue by guanxc9876** [likaia/js-screen-shot#15]

**Comment by likaia** [comment]
有的

**Comment by guanxc9876** [comment]
那个工具栏不是该固定在有选择区域的下面吗，目前是鼠标点哪里工具栏到哪里

**Comment by likaia** [comment]
不会哦
<img width="1828" alt="iShot2021-08-30 16 21 21" src="https://user-images.githubusercontent.com/35120858/131309341-cea1eff1-2982-4ae3-b8a7-99c98912b31b.png">

**Comment by guanxc9876** [comment]
![Uploading 222.png…]()

**Comment by guanxc9876** [comment]
![222](https://user-images.githubusercontent.com/53296409/131767612-9f7f8211-726f-4c3a-aba6-f02d5c878750.png)

**Comment by likaia** [comment]
你检查下你的项目吧，应该是css样式冲突了

**Comment by guanxc9876** [comment]
![1](https://user-images.githubusercontent.com/53296409/131767881-2ae22ab2-271e-4c4d-b171-bd185a90a7f9.png)
![2](https://user-images.githubusercontent.com/53296409/131767890-997c9935-05cc-4122-9422-f395932be5ae.png)

**Comment by guanxc9876** [comment]
![3](https://user-images.githubusercontent.com/53296409/131768139-170ab816-afa4-4a83-8e73-5bf589eb2d72.png)

**Comment by xiang0308** [comment]
> 那个工具栏不是该固定在有选择区域的下面吗，目前是鼠标点哪里工具栏到哪里

嗯，我也遇到同样的问题。

**Comment by xiang0308** [comment]
框选区域固定后，此时点击遮罩区域任意位置  工具栏会随着鼠标点击发生位置变化。大佬，能看看是什么问题吗？

**Comment by likaia** [comment]
> 框选区域固定后，此时点击遮罩区域任意位置 工具栏会随着鼠标点击发生位置变化。大佬，能看看是什么问题吗？

今天修复这个问题
