### ISSUE TITLE
画板输入文字超出选区，确定截图后文字超出部分不显示，生成截图后文字

### ISSUE THREAD

**Issue by jinsongen** [likaia/js-screen-shot#150]
### Version of js-screen-shot

1.9.9-rc.9

### What happened?

编辑时的布局
https://down.dingtalk.com/ddmedia/iwEcAqNqcGcDAQTREAAF0QwABrAX1SPldrLWTQXFn8cEEQoAB9IUDdUPCAAJomltCgAL0gArawk.jpg_720x720q90.jpg?auth_bizType=IM&auth_bizEntity=%7B%22cid%22:%22336450831:336450831%22,%22msgId%22:%2218358192973729%22%7D&open_id=336450831&renderWidth=4096&renderHeight=3072&renderOrientation=1&isLocal=0&bizType=im
确定后生成图片
![1400677331-0000002111_test_t1-fCGWDHQ3quddLqjBtmCI3EPDKMDlhbYp](https://github.com/likaia/js-screen-shot/assets/28554094/d5b6bc7b-9d41-444c-a307-db6657f527dd)

**Comment by likaia** [comment]
Hello @jinsongen. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @jinsongen，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by jinsongen** [comment]
编辑时的布局
https://down.dingtalk.com/ddmedia/iwEcAqNqcGcDAQTREAAF0QwABrAX1SPldrLWTQXFn8cEEQoAB9IUDdUPCAAJomltCgAL0gArawk.jpg_720x720q90.jpg?auth_bizType=IM&auth_bizEntity=%7B%22cid%22:%22336450831:336450831%22,%22msgId%22:%2218358192973729%22%7D&open_id=336450831&renderWidth=4096&renderHeight=3072&renderOrientation=1&isLocal=0&bizType=im

**Comment by jinsongen** [comment]
编辑时的布局
![Uploading IMG_20240222_165411.jpg…]()

**Comment by jinsongen** [comment]
编辑时的布局
![Uploading WX20240222-170535.png…]()

**Comment by jinsongen** [comment]
![Uploading WX20240222-170535.png…]()
