### ISSUE TITLE
文字问题：文字输入换行不生效，文字超出选区

### ISSUE THREAD

**Issue by jinsongen** [likaia/js-screen-shot#151]
### Version of js-screen-shot

1.9.9-rc.9

### What happened?

![1xz9qh1mio1lvzkbibgjofde2_0](https://github.com/likaia/js-screen-shot/assets/28554094/e9cf543a-f6e0-4c27-acbd-f5ca7e968d60)
![1xz9qh1mio1lvzkbibgjofde2_0](https://github.com/likaia/js-screen-shot/assets/28554094/35c43b8c-caa8-4629-bd74-283192171b97)

**Comment by likaia** [comment]
Hello @jinsongen. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @jinsongen，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.9-rc.9
> 
> ### Operating system and its version
> _No response_
> 
> ### Browser and its version
> _No response_
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> ![1xz9qh1mio1lvzkbibgjofde2_0](https://private-user-images.githubusercontent.com/28554094/306941763-e9cf543a-f6e0-4c27-acbd-f5ca7e968d60.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTM5MDksIm5iZiI6MTcwOTc5MzYwOSwicGF0aCI6Ii8yODU1NDA5NC8zMDY5NDE3NjMtZTljZjU0M2EtZjZlMC00YzI3LWFjYmQtZjVjYTdlOTY4ZDYwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2NDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OTMyOTM4YTQ0MzU3OGY0YzE0NWRkMWZiNmI0ZTMwZTRiOGJiMDc3NGUyNzhiZTg1OTJkZGZkNmYxODAzYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gwkc4YBi7wm2GRriI3dNKKSmym-XGI1RsTkVmtcfeLM) ![1xz9qh1mio1lvzkbibgjofde2_0](https://private-user-images.githubusercontent.com/28554094/306941764-35c43b8c-caa8-4629-bd74-283192171b97.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTM5MDksIm5iZiI6MTcwOTc5MzYwOSwicGF0aCI6Ii8yODU1NDA5NC8zMDY5NDE3NjQtMzVjNDNiOGMtY2FhOC00NjI5LWJkNzQtMjgzMTkyMTcxYjk3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2NDAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjNzRkMDk5ZjAwOTEzYmE2Yjk0ZWFkOTE1Y2M0MzM1NWVhN2M1ZmQ0ZWY3MjYzYTA2MWY3MjJjMGFmNmY0OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C1XzKgRN62Q_r2Ne3HWas4f_ha-S9jYzkxt8vX8EMII)
> 
> ### 报错信息
> _No response_

换行的问题修复了，将插件更到最新即可。
