### ISSUE TITLE
画笔、文字、箭头等颜色选择下拉箭头按钮点击没反应

### ISSUE THREAD

**Issue by jinsongen** [likaia/js-screen-shot#152]
### Version of js-screen-shot

1.9.9-rc.9

### What happened?

![7861708594330_ pic](https://github.com/likaia/js-screen-shot/assets/28554094/670d557e-fe1d-40bf-8b3e-f77750ae483f)

**Comment by likaia** [comment]
Hello @jinsongen. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @jinsongen，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> Hello @jinsongen. Your feedback has been received, and you will be notified in the issue area when the problem is resolved. 你好 @jinsongen，已收到你反馈的问题，问题解决后将在issue区域通知你。

我试了下，没问题哇
