### ISSUE TITLE
页面出现空白

### ISSUE THREAD

**Issue by zyf-2016** [likaia/js-screen-shot#153]
### Version of js-screen-shot

1.9.9-rc.11

### Operating system and its version

Windows

### Browser and its version

Google Chrome 122.0.6261.70

### What happened?

![1709118803552](https://github.com/likaia/js-screen-shot/assets/21356690/cf5ec9e5-0591-4960-9cc1-5ae4c34e41f1)

用的html2canvas模式，理论上截图应该都是天蓝色背景，但是右边出现了空白

**Comment by likaia** [comment]
Hello @zyf-2016. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @zyf-2016，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.9-rc.11
> 
> ### Operating system and its version
> Windows
> 
> ### Browser and its version
> Google Chrome 122.0.6261.70
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> ![1709118803552](https://private-user-images.githubusercontent.com/21356690/308527653-cf5ec9e5-0591-4960-9cc1-5ae4c34e41f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkxOTYyNjcsIm5iZiI6MTcwOTE5NTk2NywicGF0aCI6Ii8yMTM1NjY5MC8zMDg1Mjc2NTMtY2Y1ZWM5ZTUtMDU5MS00OTYwLTljYzEtNWFlNGMzNGU0MWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDA4MzkyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMyZDFkM2MzOTQyZmY1NTUwNjk0NTc0MDNhMzhkMWNlNjNjNzgyZTQwMjZjNTAxYWY4OTg2MWE0MDE5NTYxYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E9yG2_XIUIK3C7MOF_Z4E1lLUT14Qwtl3qkZU8YLrbQ)
> 
> 用的html2canvas模式，理论上截图应该都是天蓝色背景，但是右边出现了空白
> 
> ### 报错信息
> _No response_

页面是缩放了吗？

**Comment by zyf-2016** [comment]
是的，浏览器缩放设置的是100%。页面就是一个div元素宽高100%，用chrome浏览器100%复现，edge浏览器是正常的

**Comment by likaia** [comment]
> 是的，浏览器缩放设置的是100%。页面就是一个div元素宽高100%，用chrome浏览器100%复现，edge浏览器是正常的

代码贴一下，我试试

**Comment by zyf-2016** [comment]
<template>
    <div style="width:100vw;height:100vh;background:skyblue"></div>
</template>

<script setup lang="ts">
import ScreenShot from "js-web-screen-shot";
import { onMounted } from "vue";
onMounted(() => {
    new ScreenShot({
        enableWebRtc: false
    })
})
</script>

**Comment by zyf-2016** [comment]
```
<template>
    <div style="width:100vw;height:100vh;background:skyblue"></div>
</template>

<script setup lang="ts">
import ScreenShot from "js-web-screen-shot";
import { onMounted } from "vue";
onMounted(() => {
    new ScreenShot({
        enableWebRtc: false
    })
})
</script>
```

**Comment by zyf-2016** [comment]
chrome 121.0.6167.140版本也是正常的，应该是浏览器版本兼容问题

**Comment by zyf-2016** [comment]
不好意思，是我自己安装的扩展程序导致的，浪费您时间了
