### ISSUE TITLE
启动速度有点慢啊～～

### ISSUE THREAD

**Issue by corn-x1999** [likaia/js-screen-shot#160]
### Version of js-screen-shot

^1.9.9-rc.18

### Operating system and its version

MacOS

### Sandbox to reproduce

1

### What happened?

在windows电脑点击截图后启动速度有点慢 mac还行，浏览器出现canvas警告

### 报错信息

```shell
警告信息
```

**Comment by likaia** [comment]
Hello @corn-x1999. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @corn-x1999，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> ^1.9.9-rc.18
> 
> ### Operating system and its version
> MacOS
> 
> ### Browser and its version
> _No response_
> 
> ### Sandbox to reproduce
> 1
> 
> ### What happened?
> 在windows电脑点击截图后启动速度有点慢 mac还行，浏览器出现canvas警告
> 
> ### 报错信息
> ```shell
> 警告信息
> ```

页面dom太多了，这个没啥好办法避免
