### ISSUE TITLE
跨域导致插件打开失败

### ISSUE THREAD

**Issue by input-usename** [likaia/js-screen-shot#161]
### 问题描述

页面form中存在跨域图片，导致截图时一直空白，随后控制台显示form中的图片跨域 js-web-screen-shot.js报错

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> _No response_
> 
> ### 问题描述
> 页面form中存在跨域图片，导致截图时一直空白，随后控制台显示form中的图片跨域 js-web-screen-shot.js报错

用的哪个版本？

**Comment by input-usename** [comment]
v1.9.9

**Comment by input-usename** [comment]
> > ### js-screen-shot 的版本
> > _没有反应_
> > ### 问题描述
> > 页面form中存在跨域图片，导致截图时一直空白，随后控制台显示form中的图片跨域 js-web-screen-shot.js报错
> 
> 用哪个版本？

v1.9.9

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> _No response_
> 
> ### 问题描述
> 页面form中存在跨域图片，导致截图时一直空白，随后控制台显示form中的图片跨域 js-web-screen-shot.js报错

这个问题解决了，插件更新到1.9.9-rc.22版本即可，顺带扩展了一个参数出来https://www.kaisir.cn/js-screen-shot/docs/config/#6leo5zf5zu54mh5yqg6l295asx6lsl5zue6lcd
