### ISSUE TITLE
当页面中有img标签且src地址无法获取到图片资源时。截图控件报错。

### ISSUE THREAD

**Issue by hzboy192** [likaia/js-screen-shot#162]
### Version of js-screen-shot

1.7.9

### Operating system and its version

Windows

### Browser and its version

126.0.6478.127（正式版本） （64 位）

### Sandbox to reproduce

`在被截图的页面body中添加<img src="https://xxx.com/demo.jpg"/>然后截图`

### What happened?

截图遮罩层出现后鼠标无法选择截图区域。控制台有错误，提示图片not fond。

使用html2canvas模式截图，相关配置：
enableWebRtc: false,
loadCrossImg: true,
clickCutFullScreen: false,
wrcWindowMode: false,
hiddenScrollBar: {state: true},

页面错误不应该影响截图软件的运行，临时处理方案修改源码drawCrossImg函数中img.onerror将src替换成空白图片后按onload中的逻辑执行，截图是优化的逻辑供参考。
![2024-07-04_15-41-27](https://github.com/likaia/js-screen-shot/assets/4520051/5324512e-75a7-4733-8259-30bad9b3e0ef)

### 报错信息

```shell
报错信息见浏览器控制台错误。
```

### 处理建议
插件提供一个dom转换的onerror回调函数，将出现异常的dom对象传递给过去，让开发人员自定义实现异常修复逻辑。框架可默认实现一个异常修复方案，保证截图控件正常运行。

**Comment by likaia** [comment]
Hello @hzboy192. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @hzboy192，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.7.9
> 
> ### Operating system and its version
> Windows
> 
> ### Browser and its version
> 126.0.6478.127（正式版本） （64 位）
> 
> ### Sandbox to reproduce
> `在被截图的页面body中添加<img src="https://xxx.com/demo.jpg"/>然后截图`
> 
> ### What happened?
> 截图遮罩层出现后鼠标无法选择截图区域。控制台有错误，提示图片not fond。
> 
> 使用html2canvas模式截图，相关配置： enableWebRtc: false, loadCrossImg: true, clickCutFullScreen: false, wrcWindowMode: false, hiddenScrollBar: {state: true},
> 
> 页面错误不应该影响截图软件的运行，临时处理方案修改源码drawCrossImg函数中img.onerror将src替换成空白图片后按onload中的逻辑执行，截图是优化的逻辑供参考。 ![2024-07-04_15-41-27](https://private-user-images.githubusercontent.com/4520051/345741082-5324512e-75a7-4733-8259-30bad9b3e0ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDQyNDgsIm5iZiI6MTczMzg0Mzk0OCwicGF0aCI6Ii80NTIwMDUxLzM0NTc0MTA4Mi01MzI0NTEyZS03NWE3LTQ3MzMtODI1OS0zMGJhZDliM2UwZWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTBUMTUxOTA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTFiOWQ4YWRjOGU4NTU5ODJlMjc2YTM5M2IyZDViYTA5ZmZmMTljNDYyMTU2M2MwMGJhMWY1N2VmM2Q0YzZjNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1MtDRViYjEweczp4Tz0cRiMWXYphwLl0_zMzs4MILPk)
> 
> ### 报错信息
> ```shell
> 报错信息见浏览器控制台错误。
> ```
> 
> ### 处理建议
> 插件提供一个dom转换的onerror回调函数，将出现异常的dom对象传递给过去，让开发人员自定义实现异常修复逻辑。框架可默认实现一个异常修复方案，保证截图控件正常运行。

处理好了，插件更到1.9.9-rc.22版本，就不会报错了。顺带加了一个回调参数，具体的使用方法请移步：https://www.kaisir.cn/js-screen-shot/docs/config/#6leo5zf5zu54mh5yqg6l295asx6lsl5zue6lcd
