### ISSUE TITLE
截图后蒙层上的样式丢失

### ISSUE THREAD

**Issue by qweqwezxcasdsadzxc** [likaia/js-screen-shot#163]
### Version of js-screen-shot

1.9.9-rc.16

### What happened?

使用配置
new screenShotPlugin({ enableWebRtc: false, completeCallback: callback, closeCallback: closeFn, level: 10000, clickCutFullScreen: true, noScroll: false })
点击截图后页面页面有样式丢失的情况,而且如果是滚动盒子滚动到底部截图的时候,会自动回到页面顶部

**Comment by likaia** [comment]
Hello @qweqwezxcasdsadzxc. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @qweqwezxcasdsadzxc，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by zhongchang0213** [comment]
+1 截图后canvas绘制的图片输入框边框变粗

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.9.9-rc.16
> 
> ### Operating system and its version
> _No response_
> 
> ### Browser and its version
> _No response_
> 
> ### Sandbox to reproduce
> _No response_
> 
> ### What happened?
> 使用配置 new screenShotPlugin({ enableWebRtc: false, completeCallback: callback, closeCallback: closeFn, level: 10000, clickCutFullScreen: true, noScroll: false }) 点击截图后页面页面有样式丢失的情况,而且如果是滚动盒子滚动到底部截图的时候,会自动回到页面顶部
> 
> ### 报错信息
> _No response_

h2c模式是这样的，他支持的不够完美
