### ISSUE TITLE
pnpm项目使用npm下载插件报错

### ISSUE THREAD

**Issue by wangmou-cmd** [likaia/js-screen-shot#166]
### Version of js-screen-shot

1.9.9-rc.21

### Operating system and its version

Windows

### Browser and its version

无

### What happened?

使用npm install js-web-screen-shot --save进行下拉报错：
PS D:\chenm\vue\取号机> npm install js-web-screen-shot --save
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qd\AppData\Local\npm-cache\_logs\2024-10-16T02_40_03_933Z-debug-0.log
PS D:\chenm\vue\取号机> 

### 报错信息

```shell
PS D:\chenm\vue\取号机> npm install js-web-screen-shot --save
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\qd\AppData\Local\npm-cache\_logs\2024-10-16T02_40_03_933Z-debug-0.log
PS D:\chenm\vue\取号机>
```

**Comment by likaia** [comment]
Hello @wangmou-cmd. Your feedback has been received, and you will be notified in the issue area when the problem is resolved.
你好 @wangmou-cmd，已收到你反馈的问题，问题解决后将在issue区域通知你。

**Comment by likaia** [comment]
? 如果不出意外的话，你下载其他依赖包也会报错吧，检查下网络环境看看

**Comment by wangmou-cmd** [comment]
我的项目是pnpm vite创建的，node版本是16.20.2，npm版本是8.19.4，升级到18.20.2跟10.5.0也是报这个错误

**Comment by wangmou-cmd** [comment]
> ？ 如果不出意外的话，你下载其他依赖包染色体报错吧，检查下网络环境看看

我连接的是公司的网，检查网络连接结果是：你已连接到Internet。我们未发现你的网络有任何问题
关掉梯子重新下拉也是报错

**Comment by Epic-Deno** [comment]
> 我的项目是pnpm vite创建的，node版本是16.20.2，npm版本是8.19.4，升级到18.20.2跟10.5.0也是报这个错误

你问题很简单： pnpm vite创建的， 决定了你依赖下载方式是pnpm, 你装包的时候就需要用pnpm 来安装, npm和pnpm的包管理原理你可以去看下

**Comment by Epic-Deno** [comment]
> > ？ 如果不出意外的话，你下载其他依赖包染色体报错吧，检查下网络环境看看
> 
> 我连接的是公司的网，检查网络连接结果是：你已连接到Internet。我们未发现你的网络有任何问题 关掉梯子重新下拉也是报错

<img width="647" alt="image" src="https://github.com/user-attachments/assets/c55cf62a-9968-4fd2-b659-fd3e26ac9192">

**Comment by wangmou-cmd** [comment]
> > 我的项目是pnpm vite创建的，node版本是16.20.2，npm版本是8.19.4，升级到18.20.2跟10.5.0也是报这个错误
> 
> 你问题很简单： pnpm vite创建的， 决定了你依赖下载方式是pnpm, 你装包的时候就需要用pnpm 来安装, npm和pnpm的包管理原理你可以去看下

好的，谢谢你的解答，我已经成功

**Comment by wangmou-cmd** [comment]
> > > ？ 如果不出意外的话，你下载其他依赖包染色体报错吧，检查下网络环境看看
> > 
> > 
> > 我连接的是公司的网，检查网络连接结果是：你已连接到Internet。我们未发现你的网络有任何问题 关掉梯子重新下拉也是报错
> 
> <img alt="图像" width="647" src="https://private-user-images.githubusercontent.com/74635349/376871419-c55cf62a-9968-4fd2-b659-fd3e26ac9192.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwNDgyNjAsIm5iZiI6MTcyOTA0Nzk2MCwicGF0aCI6Ii83NDYzNTM0OS8zNzY4NzE0MTktYzU1Y2Y2MmEtOTk2OC00ZmQyLWI2NTktZmQzZTI2YWM5MTkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE2VDAzMDYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZDk0YjYxMTBjOThhOTNjMjE5YjBlM2I3MTBmMzlhMzgyZjk2NGRlYTJlYTA3NGUyMGRkNWRiM2ZlYWQ2MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2qTelh5cfJ-SDEycDPjEC_eEgfJRobtZZNiDroZ66G0">

好的，谢谢你
