### ISSUE TITLE
截图工具栏支持添加自定义工具

### ISSUE THREAD

**Issue by ecjtu-YangkaiLin** [likaia/js-screen-shot#168]
### Version of js-screen-shot

最新版

### 你的想法是什么?

有没有可能支持在截图工具栏中添加自定义的工具？例如，我想在工具栏添加一个OCR的按钮，可以直接进行OCR识别。
当前版本似乎只能自定义现有工具的图标。

**Comment by likaia** [comment]
Hello @ecjtu-YangkaiLin. Your suggestion has been received, and you will be notified in the issue area after the evaluation is completed.
你好 @ecjtu-YangkaiLin，已收到你的建议，评估完成后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 最新版
> 
> ### 你的想法是什么?
> 有没有可能支持在截图工具栏中添加自定义的工具？例如，我想在工具栏添加一个OCR的按钮，可以直接进行OCR识别。 当前版本似乎只能自定义现有工具的图标。

这个功能在开发了（大概完成90%），最近在忙考驾照的事情，暂且放着了
