### ISSUE TITLE
非webrtc截图优化内容

### ISSUE THREAD

**Issue by kankanai** [likaia/js-screen-shot#171]
### Version of js-screen-shot

1.11.11

### 你的想法是什么?

是这样的，很喜欢这个编辑图片功能，但是我是内网环境，所以只能是 enableWebRtc: false，但是html2canvas样式兼容很不好，于是我找到一个仓库，https://www.npmjs.com/package/html-to-image，这个截图是完美的，一比一复现界面，且支持多种文件格式，我导出为了png，它返回的是data:image/png;base64,iVBORw0KGgoAAAA这种，我想有没有可能集成到这个仓库呢？比如1:替换默认的html2canvas。2.支持直接导入图片，然后进行编辑

**Comment by likaia** [comment]
Hello @kankanai. Your suggestion has been received, and you will be notified in the issue area after the evaluation is completed.
你好 @kankanai，已收到你的建议，评估完成后将在issue区域通知你。

**Comment by likaia** [comment]
> ### Version of js-screen-shot
> 1.11.11
> 
> ### 你的想法是什么?
> 是这样的，很喜欢这个编辑图片功能，但是我是内网环境，所以只能是 enableWebRtc: false，但是html2canvas样式兼容很不好，于是我找到一个仓库，[https://www.npmjs.com/package/html-to-image，这个截图是完美的，一比一复现界面，且支持多种文件格式，我导出为了png，它返回的是data:image/png;base64,iVBORw0KGgoAAAA这种，我想有没有可能集成到这个仓库呢？比如1:替换默认的html2canvas。2.支持直接导入图片，然后进行编辑](https://www.npmjs.com/package/html-to-image%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%88%AA%E5%9B%BE%E6%98%AF%E5%AE%8C%E7%BE%8E%E7%9A%84%EF%BC%8C%E4%B8%80%E6%AF%94%E4%B8%80%E5%A4%8D%E7%8E%B0%E7%95%8C%E9%9D%A2%EF%BC%8C%E4%B8%94%E6%94%AF%E6%8C%81%E5%A4%9A%E7%A7%8D%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F%EF%BC%8C%E6%88%91%E5%AF%BC%E5%87%BA%E4%B8%BA%E4%BA%86png%EF%BC%8C%E5%AE%83%E8%BF%94%E5%9B%9E%E7%9A%84%E6%98%AFdata:image/png;base64,iVBORw0KGgoAAAA%E8%BF%99%E7%A7%8D%EF%BC%8C%E6%88%91%E6%83%B3%E6%9C%89%E6%B2%A1%E6%9C%89%E5%8F%AF%E8%83%BD%E9%9B%86%E6%88%90%E5%88%B0%E8%BF%99%E4%B8%AA%E4%BB%93%E5%BA%93%E5%91%A2%EF%BC%9F%E6%AF%94%E5%A6%821:%E6%9B%BF%E6%8D%A2%E9%BB%98%E8%AE%A4%E7%9A%84html2canvas%E3%80%822.%E6%94%AF%E6%8C%81%E7%9B%B4%E6%8E%A5%E5%AF%BC%E5%85%A5%E5%9B%BE%E7%89%87%EF%BC%8C%E7%84%B6%E5%90%8E%E8%BF%9B%E8%A1%8C%E7%BC%96%E8%BE%91)

导入图片是支持的，这是API：[自定义截图内容](https://www.kaisir.cn/js-screen-shot/docs/config/#6ieq5a6a5lmj5oiq5zu5yaf5a65)

**Comment by kankanai** [comment]
> > ### Version of js-screen-shot
> > 1.11.11
> > ### 你的想法是什么?
> > 是这样的，很喜欢这个编辑图片功能，但是我是内网环境，所以只能是 enableWebRtc: false，但是html2canvas样式兼容很不好，于是我找到一个仓库，[https://www.npmjs.com/package/html-to-image，这个截图是完美的，一比一复现界面，且支持多种文件格式，我导出为了png，它返回的是data:image/png;base64,iVBORw0KGgoAAAA这种，我想有没有可能集成到这个仓库呢？比如1:替换默认的html2canvas。2.支持直接导入图片，然后进行编辑](https://www.npmjs.com/package/html-to-image%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%88%AA%E5%9B%BE%E6%98%AF%E5%AE%8C%E7%BE%8E%E7%9A%84%EF%BC%8C%E4%B8%80%E6%AF%94%E4%B8%80%E5%A4%8D%E7%8E%B0%E7%95%8C%E9%9D%A2%EF%BC%8C%E4%B8%94%E6%94%AF%E6%8C%81%E5%A4%9A%E7%A7%8D%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F%EF%BC%8C%E6%88%91%E5%AF%BC%E5%87%BA%E4%B8%BA%E4%BA%86png%EF%BC%8C%E5%AE%83%E8%BF%94%E5%9B%9E%E7%9A%84%E6%98%AFdata:image/png;base64,iVBORw0KGgoAAAA%E8%BF%99%E7%A7%8D%EF%BC%8C%E6%88%91%E6%83%B3%E6%9C%89%E6%B2%A1%E6%9C%89%E5%8F%AF%E8%83%BD%E9%9B%86%E6%88%90%E5%88%B0%E8%BF%99%E4%B8%AA%E4%BB%93%E5%BA%93%E5%91%A2%EF%BC%9F%E6%AF%94%E5%A6%821:%E6%9B%BF%E6%8D%A2%E9%BB%98%E8%AE%A4%E7%9A%84html2canvas%E3%80%822.%E6%94%AF%E6%8C%81%E7%9B%B4%E6%8E%A5%E5%AF%BC%E5%85%A5%E5%9B%BE%E7%89%87%EF%BC%8C%E7%84%B6%E5%90%8E%E8%BF%9B%E8%A1%8C%E7%BC%96%E8%BE%91)
> 
> 导入图片是支持的，这是API：[自定义截图内容](https://www.kaisir.cn/js-screen-shot/docs/config/#6ieq5a6a5lmj5oiq5zu5yaf5a65)

太强啦，感谢

**Comment by likaia** [comment]
> > > ### Version of js-screen-shot
> > > 1.11.11
> > > ### 你的想法是什么?
> > > 是这样的，很喜欢这个编辑图片功能，但是我是内网环境，所以只能是 enableWebRtc: false，但是html2canvas样式兼容很不好，于是我找到一个仓库，[https://www.npmjs.com/package/html-to-image，这个截图是完美的，一比一复现界面，且支持多种文件格式，我导出为了png，它返回的是data:image/png;base64,iVBORw0KGgoAAAA这种，我想有没有可能集成到这个仓库呢？比如1:替换默认的html2canvas。2.支持直接导入图片，然后进行编辑](https://www.npmjs.com/package/html-to-image%EF%BC%8C%E8%BF%99%E4%B8%AA%E6%88%AA%E5%9B%BE%E6%98%AF%E5%AE%8C%E7%BE%8E%E7%9A%84%EF%BC%8C%E4%B8%80%E6%AF%94%E4%B8%80%E5%A4%8D%E7%8E%B0%E7%95%8C%E9%9D%A2%EF%BC%8C%E4%B8%94%E6%94%AF%E6%8C%81%E5%A4%9A%E7%A7%8D%E6%96%87%E4%BB%B6%E6%A0%BC%E5%BC%8F%EF%BC%8C%E6%88%91%E5%AF%BC%E5%87%BA%E4%B8%BA%E4%BA%86png%EF%BC%8C%E5%AE%83%E8%BF%94%E5%9B%9E%E7%9A%84%E6%98%AFdata:image/png;base64,iVBORw0KGgoAAAA%E8%BF%99%E7%A7%8D%EF%BC%8C%E6%88%91%E6%83%B3%E6%9C%89%E6%B2%A1%E6%9C%89%E5%8F%AF%E8%83%BD%E9%9B%86%E6%88%90%E5%88%B0%E8%BF%99%E4%B8%AA%E4%BB%93%E5%BA%93%E5%91%A2%EF%BC%9F%E6%AF%94%E5%A6%821:%E6%9B%BF%E6%8D%A2%E9%BB%98%E8%AE%A4%E7%9A%84html2canvas%E3%80%822.%E6%94%AF%E6%8C%81%E7%9B%B4%E6%8E%A5%E5%AF%BC%E5%85%A5%E5%9B%BE%E7%89%87%EF%BC%8C%E7%84%B6%E5%90%8E%E8%BF%9B%E8%A1%8C%E7%BC%96%E8%BE%91)
> > 
> > 
> > 导入图片是支持的，这是API：[自定义截图内容](https://www.kaisir.cn/js-screen-shot/docs/config/#6ieq5a6a5lmj5oiq5zu5yaf5a65)
> 
> 太强啦，感谢

没事，你记得把版本号写到最新，我忘记是在哪个版本扩展的这个API了。
