### ISSUE TITLE
设置level后，文字标注的输入域看不到。

### ISSUE THREAD

**Issue by shanyueee** [likaia/js-screen-shot#18]
我的配置
![image](https://user-images.githubusercontent.com/60082124/139225338-dc72a146-4c32-4bb8-8414-26ee86e8d3e1.png)
截图时输入效果
![image](https://user-images.githubusercontent.com/60082124/139225963-19aa9882-1bd3-466b-9503-ffd3578d086c.png)
输入后，文字失去光标后的效果
![image](https://user-images.githubusercontent.com/60082124/139225760-b56f0c52-35c1-4541-b734-a643ed0b539b.png)

还有，enableWebRtc模式的时候，浏览器会弹窗，所以将enableWebRtc设置false，设置后ifream的页面不显示，但是这个ifream页面本身就是允许跨域的，我页面中是也调的通的。
截图前
![image](https://user-images.githubusercontent.com/60082124/139226993-c9b26d7a-9ab0-4d6e-88bb-4ddec2dc3ea5.png)
截图后
![image](https://user-images.githubusercontent.com/60082124/139226893-0b97d159-44c0-488d-b451-3a18d11f5cc4.png)

**Comment by likaia** [comment]
> > 第二个问题，即使你服务端允许跨域，图片与网站不在同一个源，html2canvas是没法做到获取图片的
> 
> 明白，谢谢啦！还有一个个人建议，仅供参考（当页面有标注后，截图是不允许拖动的，也不允许调节大小的，这个时候的窗口四周的拖动点，最好隐藏掉，不然会给人一种可操作的错觉。）

好，谢谢建议，我今天改下
