### ISSUE TITLE
html2canvas模式蒙层 加载慢

### ISSUE THREAD

**Issue by abiaoLHB** [likaia/js-screen-shot#19]
大神，如题，该模式下从点击截图 到 黑色蒙版显示到窗口中，需要5秒左右怎么搞？给人的感觉是，点了截图，没反应一样。然后等5秒，黑色蒙版出来了。。

**Comment by likaia** [comment]
我加个回调事件吧，你可以自己根据需求来决定这5秒做什么。

**Comment by likaia** [comment]
加了个triggerCallback事件，插件更新到1.3.0，具体使用方法看文档即可。
