### ISSUE TITLE
运行dist下的html文件,实例化对象,报错document.body 为null

### ISSUE THREAD

**Issue by garmin21** [likaia/js-screen-shot#2]
![image](https://user-images.githubusercontent.com/51853339/108652935-47346d00-7500-11eb-8df7-7812263829de.png)

**Comment by likaia** [comment]
不能直接这么用的，你看下我的插件使用文档，你要等dom加载完毕后再实例化，如下所示：
`<script>
  window.onload = ()=> {
    new screenShotPlugin();
  }
</script>`


![image](https://user-images.githubusercontent.com/35120858/108653263-f96c3480-7500-11eb-9d25-6dd53d4ce5aa.png)
