### ISSUE TITLE
取消分享又回调事件吗

### ISSUE THREAD

**Issue by QiuAnn** [likaia/js-screen-shot#20]
现在是点击截图，然后又想”取消“，想在“取消”的时候做一些操作。能否把取消分享的回调事件暴露出来？
![image](https://user-images.githubusercontent.com/31036255/140484330-d2c98515-e848-4f13-bd00-067376d0ec43.png)

**Comment by likaia** [comment]
有的，我加一下

**Comment by likaia** [comment]
加好了，插件更新到1.3.0就可以使用了，加了个cancelCallback参数，具体使用方法看文档即可
