### ISSUE TITLE
当缩小浏览器窗口时进行截图，下面的图标样式错乱了

### ISSUE THREAD

**Issue by QiuAnn** [likaia/js-screen-shot#21]
![image](https://user-images.githubusercontent.com/31036255/140485439-8e9f73e2-1353-4ba4-887d-8fa4c30fcb84.png)
![~Y S%(CW`71CKNE)HYWDT(O](https://user-images.githubusercontent.com/31036255/140485531-69906b3c-74cf-4e71-b39e-b33aa9f0503c.png)

left 的位置计算有问题？？

**Comment by likaia** [comment]
不会的，我专门测了下
![image](https://user-images.githubusercontent.com/35120858/140611852-79b29e74-4f68-4020-9d3b-3401e08da104.png)

**Comment by QiuAnn** [comment]
> 不会的，我专门测了下 ![image](https://user-images.githubusercontent.com/35120858/140611852-79b29e74-4f68-4020-9d3b-3401e08da104.png)
我看到了出现滚动条？但是你这张图截得的是有点小。截屏的时候尝试截到要滑动滚动条也不会嘛【一边截图一遍拖动滚动条】？
你们测试的地址也会出现这个问题呢?
![image](https://user-images.githubusercontent.com/31036255/140674896-bbf1a060-3be8-4edd-9910-5c7ee380eecc.png)

**Comment by QiuAnn** [comment]
重现步骤2: 在截图的界面时，缩小窗口也一样。
![image](https://user-images.githubusercontent.com/31036255/140675064-e0877588-f806-4f0a-962a-85356fefa678.png)

**Comment by likaia** [comment]
截图的界面缩放后，这里没处理，只要正常使用没问题就行
