### ISSUE TITLE
可以取消用户选择分享的弹窗吗？

### ISSUE THREAD

**Issue by Robinbiao** [likaia/js-screen-shot#22]
截屏时getDisplayMedia api需要用户选择分享窗口，可以默认当前触发的界面，过滤这步选择弹窗提示吗？

**Comment by likaia** [comment]
这个是不能的，如果需要的话，你可以选择html2canvas模式

**Comment by Robinbiao** [comment]
html2canvas 这个模式对页面内嵌iframe有问题 ，iframe内容无法显示
