### ISSUE TITLE
fix: 截图效果不正确

### ISSUE THREAD

**Issue by wll8** [likaia/js-screen-shot#28]
注意看 button 的边缘在截图时被改变了。

## 期望效果
![image](https://user-images.githubusercontent.com/28223260/144584071-13f655d8-0a68-43cb-9238-59ef2e011159.png)

## 得到效果
![image](https://user-images.githubusercontent.com/28223260/144584234-64d79ae0-24a4-4207-a78e-bff735010fbd.png)

## 环境
- js-web-screen-shot@1.5.2
- chrome@96.0.4664.45

## 复现步骤
- 运行下面的代码
- 点击 `点我`，再点击 `勾` 确定图标
- 在浏览器控制台中打开 callback 回调的 base64

``` html
<head>
  <meta charset="UTF-8">
  <script src="https://cdn.jsdelivr.net/npm/js-web-screen-shot@1.5.2/dist/screenShotPlugin.umd.js"></script>
  <title>屏幕截图</title>
</head>
<body>
  <button id="btn">点我</button>
  <div>
    <button>一个按钮</button>
    <p>这是一些其他元素……</p>
  </div>
  <script>
    btn.onclick = () => {
      // 截图确认按钮回调函数
      const callback = (base64) => {
        console.log(`callback`, base64)
      }
      // 截图取消时的回调函数
      const closeFn = () => {
        console.log(`closeFn`)
      }
      new screenShotPlugin({ enableWebRtc: false, completeCallback: callback, closeCallback: closeFn })
    }
  </script>
</body>
</html>
```

**Comment by likaia** [comment]
边框加粗了，估计是html2canvas的锅，webrtc模式应该没这个问题

**Comment by wll8** [comment]
客户拒绝使用 webrtc 模式

**Comment by likaia** [comment]
那就难搞了，html2canvas或多或少有点不完美

**Comment by likaia** [comment]
大体效果是完美的，这些细节不影响大局

**Comment by wll8** [comment]
滚去给 html2canvas 提 bug /手动狗头

**Comment by likaia** [comment]
这个问题找到方案了，晚点更新下插件，你可以加下我微信，弄好了第一时间告诉你。
我微信号：baymax-kt

**Comment by likaia** [comment]
放弃了，这个方案行不通，等html2canvas更新吧。
