### ISSUE TITLE
赞一个！我想把这个插件弄到Eletron项目里

### ISSUE THREAD

**Issue by Jony1943** [likaia/js-screen-shot#31]
目前有个需求是在整个屏幕内截图，用的React+Electron，不知道这个行不行?

**Comment by likaia** [comment]
那得看Electron是否支持webrtc了

**Comment by Jony1943** [comment]
> 那得看Electron是否支持webrtc了

应该是利用electron创建一个全屏的透明窗口，然后加载一个网页，网页内只需要使用这个插件

**Comment by likaia** [comment]
webrtc模式目前在Electron中不被支持的，只能用html2canvas模式
