### ISSUE TITLE
如何将截屏蒙版canvas绘制在全屏？

### ISSUE THREAD

**Issue by LibertyNLP** [likaia/js-screen-shot#34]
截屏之后蒙版只在相应引入ts的html内出现，这样我在使用irame嵌套的网页里使用的时候，蒙版的范围就很小，请问要怎样才能让截图蒙版充满整个屏幕呢？
如下图，绘图框仅出现在右侧小部分范围，无法显示全屏
![image](https://user-images.githubusercontent.com/94671339/145658807-59f08b69-0736-4d57-bcbd-83d06bcf3cff.png)

**Comment by likaia** [comment]
你这个放到iframe里了😂  没办法，他超不出来的，你得把截图插件放在全局

**Comment by LibertyNLP** [comment]
这样啊，那我明白了，多谢解答，再次感谢你做的项目，对我帮助非常大

**Comment by likaia** [comment]
嘿嘿，没事，觉得不错的话，就点个star吧

**Comment by LibertyNLP** [comment]
那是自然，昨天已点star
