### ISSUE TITLE
截图清晰度还可以提高吗？

### ISSUE THREAD

**Issue by LibertyNLP** [likaia/js-screen-shot#36]
截图之后发现清晰度不是很高，请问有什么设置可以提高截图的清晰度吗？

**Comment by likaia** [comment]
你是用的mac或者高分屏吧，这个没办法，你在windows的1080p分辨率下很清晰的。

**Comment by LibertyNLP** [comment]
我确实用的是高分屏，2.8K的，待会用1080p的屏幕试一下

**Comment by likaia** [comment]
嗯嗯
