### ISSUE TITLE
可以修改drawimage的顺序吗？

### ISSUE THREAD

**Issue by LibertyNLP** [likaia/js-screen-shot#37]
可以在确认分享之后就把图片绘制在canvas里面吗？现在的逻辑似乎是要先点击拖动之后才会把截图绘制在canvas上面，当截图页面和截取页面不一样时就会比较奇怪，因为没有拖动选择则不会显示出待选图片

没有按住并拖动鼠标时
![image](https://user-images.githubusercontent.com/94671339/145828122-a786e2fd-ebad-4d91-aae4-ecf4f325dae9.png)

按住并拖动鼠标时
![image](https://user-images.githubusercontent.com/94671339/145828046-2b4395c3-c91c-43d7-ada7-6f8ee0901d8b.png)

**Comment by likaia** [comment]
暂时不支持，我晚点加个参数支持下。

**Comment by LibertyNLP** [comment]
感谢，期待

**Comment by likaia** [comment]
支持上了，插件更新到1.6.1即可。

**Comment by likaia** [comment]
具体是哪个参数，查阅文档即可。

**Comment by LibertyNLP** [comment]
用上了，很好用，感谢~
