### ISSUE TITLE
截图被压缩了，救救孩子吧

### ISSUE THREAD

**Issue by micahh28** [likaia/js-screen-shot#38]
页面元素超过一屏时，画面会挤压
![image](https://user-images.githubusercontent.com/41413559/147727943-7cf009f1-e1a6-4a7c-a4f8-68809fe71ea0.png)
![image](https://user-images.githubusercontent.com/41413559/147728038-f7280dd0-4d89-451d-bd27-d1af0603f3f7.png)

示例代码
<meta charset="utf-8">
<html>
<head>
	<meta charset="utf-8" />
	<title></title>
</head>
<body>
		<div>
			<button onclick="screenShotStart()">截图</button>
			
			<ul><li>1</li><li>2</li><li>3</li><li>4</li><li>5</li><li>6</li><li>7</li><li>8</li><li>9</li><li>10</li><li>11</li><li>12</li><li>13</li><li>14</li><li>15</li><li>16</li><li>17</li><li>18</li><li>19</li><li>20</li><li>21</li><li>22</li><li>23</li><li>24</li><li>25</li><li>26</li><li>27</li><li>28</li><li>29</li><li>30</li><li>31</li><li>32</li><li>33</li><li>34</li><li>35</li><li>36</li><li>37</li><li>38</li><li>39</li><li>40</li><li>41</li><li>42</li><li>43</li><li>44</li><li>45</li><li>46</li><li>47</li><li>48</li><li>49</li><li>50</li><li>51</li><li>52</li><li>53</li><li>54</li><li>55</li><li>56</li><li>57</li><li>58</li><li>59</li><li>60</li><li>61</li><li>62</li><li>63</li><li>64</li><li>65</li><li>66</li><li>67</li><li>68</li><li>69</li><li>70</li><li>71</li><li>72</li><li>73</li><li>74</li><li>75</li><li>76</li><li>77</li><li>78</li><li>79</li><li>80</li><li>81</li><li>82</li><li>83</li><li>84</li><li>85</li><li>86</li><li>87</li><li>88</li><li>89</li><li>90</li><li>91</li><li>92</li><li>93</li><li>94</li><li>95</li><li>96</li><li>97</li><li>98</li><li>99</li><li>100</li></ul>
		</div>
		
		<script src="./screenShotPlugin.umd.js"></script>
		
		<script>
		
			// 截图确认按钮回调函数
		    const callback = (base64) =>{
		      console.log(base64);
		    }
		    // 截图取消时的回调函数
		    const closeFn = ()=>{
		      console.log("截图窗口关闭");
		    }
			
			function screenShotStart(){
				new screenShotPlugin({enableWebRtc: false, completeCallback: callback,closeCallback: closeFn});
			}
		</script>
	</body>
</html>

**Comment by likaia** [comment]
这种情况，你可以自己传截图容器的宽高
