### ISSUE TITLE
可选参数里能配置 zIndex吗 

### ISSUE THREAD

**Issue by hualvm** [likaia/js-screen-shot#4]
当页面中 存在 zIndex的时候，你的<canvas id="screenShotContainer" width="1920" height="1057" style="display: block; cursor: default;"></canvas> 层级没有设置，建议在配置项里可以自由设置

**Comment by likaia** [comment]
哈哈哈 大意了，忽略这个问题了，我晚点加一下。

**Comment by likaia** [comment]
可以配置了，更新下插件即可
