### ISSUE TITLE
求解vue2上不能用这个吗？ 为什么点击截图显示要分享的屏幕？

### ISSUE THREAD

**Issue by sanguineman91** [likaia/js-screen-shot#40]
![image](https://user-images.githubusercontent.com/27845011/149051782-c4ef1df8-4561-47a9-8ed9-14926eb4aea7.png)

**Comment by likaia** [comment]
可以用的，弹出这个是因为你用的webrtc模式的截屏

**Comment by zhanghan19** [comment]
大佬能不能使用 webrtc 截图 并且不提示分享，默认是分享当前标签页
原因：我遇到的场景是 页面的内容是用canvas 画的东西特别多，使用html2canvas模式截图，特别慢要16s，我发现使用webrtc 截图速度很快但是多了一步分享操作感觉没有必要，所以我想取消分享这一步
