### ISSUE TITLE
使用webrtc模式截屏，蒙层中会有鼠标残留

### ISSUE THREAD

**Issue by nicaishi** [likaia/js-screen-shot#42]
![图片](https://user-images.githubusercontent.com/34568391/153319154-9900f0a7-d2bc-42fd-8f2f-92280cc5d846.png)

**Comment by likaia** [comment]
😂这个问题确实存在，目前没想到解决方案

**Comment by nicaishi** [comment]
大佬，可不可以在绘制蒙层之前把鼠标样式设置为none，绘制之后再显示出来？

**Comment by likaia** [comment]
试过了😂  没用

**Comment by koalaink** [comment]
可以通过样式将光标隐藏调
![image](https://github.com/likaia/js-screen-shot/assets/22545422/17594c4e-b710-44e8-b73e-5bdb74777f92)
![image](https://github.com/likaia/js-screen-shot/assets/22545422/5ad8f76d-ff54-444b-958c-55851a51e509)
