### ISSUE TITLE
引入组件后，与自身代码冲突

### ISSUE THREAD

**Issue by 294153753** [likaia/js-screen-shot#44]
引入组件后，与自身代码冲突，报错“对象不支持”finally“属性或方法

![17130D89-9B43-4ED1-BAC7-0B77871C69F3](https://user-images.githubusercontent.com/18255305/156513467-0e33a4f3-6f5a-4c0f-9a6a-791eda1203eb.jpeg)

靠近ie会变的不幸

**Comment by likaia** [comment]
IE啊，这是个棘手的问题
