### ISSUE TITLE
使用html2canvas截图，百度地图不显示

### ISSUE THREAD

**Issue by MingGuGu** [likaia/js-screen-shot#48]
![1647499598020](https://user-images.githubusercontent.com/38693829/158752559-050d8aac-9a57-4ef4-bcbc-2cdd4c1d7583.png)

**Comment by MingGuGu** [comment]
@likaia

**Comment by likaia** [comment]
这个没办法😂 html2canvas的局限性太大了，webrtc是没问题的。

**Comment by MingGuGu** [comment]
webrtc会截取浏览器顶部的标签栏导航栏和书签栏，，这样的话页面底部的部分就看不到了，，有没有办法可以只截取页面body部分的呢？

**Comment by likaia** [comment]
没有办法
