### ISSUE TITLE
webrtc截图的功能感觉没有实时播放选中的窗口的内容

### ISSUE THREAD

**Issue by Ray8716397** [likaia/js-screen-shot#49]
![Screenshot from 2022-04-20 17-40-00](https://user-images.githubusercontent.com/45814273/164199737-786cbd71-d2f0-4f41-a52c-173f8e3b059c.png)

**Comment by Ray8716397** [comment]
选完要截图的窗口后,开始截图时canvas没有预览出画面,就像上图一样灰色的,要滑动鼠标框选截图区域才会画出画面,这个bug怎么弄

**Comment by likaia** [comment]
> 选完要截图的窗口后,开始截图时canvas没有预览出画面,就像上图一样灰色的,要滑动鼠标框选截图区域才会画出画面,这个bug怎么弄


文档呦参数可以配置的。
<img width="992" alt="image" src="https://user-images.githubusercontent.com/35120858/165751718-224c428c-3db2-46fd-8a13-89deee69353e.png">
