### ISSUE TITLE
蒙层的高度和宽度是视口的宽高，只有点击蒙层后宽高才会变成配置的宽高（canvasWidth，canvasHeight）

### ISSUE THREAD

**Issue by whale-jung** [likaia/js-screen-shot#54]
![image](https://user-images.githubusercontent.com/80868414/174726690-4651eb53-71f3-44a4-9907-d824c793362f.png)
![image](https://user-images.githubusercontent.com/80868414/174727145-8efa29c9-8cd3-45f7-bf2e-7b25977a049d.png)
html2canvas和webRtc都是这种情况

**Comment by likaia** [comment]
OK周六我看下这个问题

**Comment by likaia** [comment]
已修复，插件更新至1.7.0即可
