### ISSUE TITLE
大佬，有个错误提示帮忙看看啊

### ISSUE THREAD

**Issue by zhuangYuFeiHelloGit** [likaia/js-screen-shot#56]
![image](https://user-images.githubusercontent.com/17961466/174994627-28e9cfe9-7d66-4773-992c-41dd3f5a731e.png)

**Comment by zhuangYuFeiHelloGit** [comment]
还有我怎么才能直接展示截图页面，而不是现有一个这个提示啊，求助
![image](https://user-images.githubusercontent.com/17961466/174994902-3db332f4-5b5e-462f-820b-c1dfaa86b9ad.png)

**Comment by zhuangYuFeiHelloGit** [comment]
大佬，我已经知道了设置成 enableWebRtc: false, 就不会弹窗了。
但是我现在的问题是，我有一个 iFrame，里面加载的 pdf，我如果用 enableWebRtc: false 截屏，是无法截取到 iFrame里面加载的pdf 的，请问有什么思路吗

**Comment by likaia** [comment]
> 大佬，我已经知道了设置成 enableWebRtc: false, 就不会弹窗了。 但是我现在的问题是，我有一个 iFrame，里面加载的 pdf，我如果用 enableWebRtc: false 截屏，是无法截取到 iFrame里面加载的pdf 的，请问有什么思路吗

不好意思😂，刚看到你的提问，昨天太忙了，忘记回复你了。目前想截取iframe里的东西只能用webrtc

**Comment by zhuangYuFeiHelloGit** [comment]
> > 大佬，我已经知道了设置成 enableWebRtc: false, 就不会弹窗了。 但是我现在的问题是，我有一个 iFrame，里面加载的 pdf，我如果用 enableWebRtc: false 截屏，是无法截取到 iFrame里面加载的pdf 的，请问有什么思路吗
> 
> 不好意思😂，刚看到你的提问，昨天太忙了，忘记回复你了。目前想截取iframe里的东西只能用webrtc

嗯嗯好的。一楼的问题你遇到过吗😂

**Comment by likaia** [comment]
> 

没遇到过，项目重启试试？

**Comment by likaia** [comment]
> > > 大佬，我已经知道了设置成 enableWebRtc: false, 就不会弹窗了。 但是我现在的问题是，我有一个 iFrame，里面加载的 pdf，我如果用 enableWebRtc: false 截屏，是无法截取到 iFrame里面加载的pdf 的，请问有什么思路吗
> > 
> > 
> > 不好意思😂，刚看到你的提问，昨天太忙了，忘记回复你了。目前想截取iframe里的东西只能用webrtc
> 
> 嗯嗯好的。一楼的问题你遇到过吗😂

没遇到过，项目重启试试？
