### ISSUE TITLE
绘制这个截图时，背景图片变得模糊了。而且图片也偏移了

### ISSUE THREAD

**Issue by zhangyusheng0373** [likaia/js-screen-shot#6]
![Jietu20210506-113719](https://user-images.githubusercontent.com/31118613/117238482-8d427100-ae5f-11eb-81bb-36a83d83bcf7.jpg)

**Comment by likaia** [comment]
emmm，是有这个问题，模糊问题应该还好吧。偏移那里位置酸的不太对
