### ISSUE TITLE
开启 clickCutFullScreen 全屏 时，工具栏错位了，急

### ISSUE THREAD

**Issue by iZaiZaiA** [likaia/js-screen-shot#62]
开启 clickCutFullScreen 全屏 时，在工具栏上，随便点开一个箭头或者框框，主工具栏，就会被顶走，然后，就回不来了，而且，选择颜色的，也显示不全。。。

<img width="505" alt="image" src="https://user-images.githubusercontent.com/26807649/180117053-061bd7ed-dedc-4b33-84a6-888aa5960c4d.png">

如果可以的话，建议给工具栏加一个拖动功能，全屏时，可以随意拖动的，避免被挡住要操作的地方。
不过，如果拖动工具栏，那么，工具栏下的配置栏，在显示时，也要跟随改变位置。

另外，输入文本那个，不能修改文本颜色吗？

**Comment by likaia** [comment]
OK，我空闲了处理下这个问题。

**Comment by iZaiZaiA** [comment]
> OK，我空闲了处理下这个问题。

好的，好的，谢谢

**Comment by iZaiZaiA** [comment]
> OK，我空闲了处理下这个问题。

最新 1.7.4 版本，全屏截图时，溢出的问题还是存在。当你点击工具栏其中一个功能后，就会溢出，滚动也没用。

<img width="553" alt="image" src="https://user-images.githubusercontent.com/26807649/194810370-b0a15eb6-5796-48d3-93c0-f1c3194b76c1.png">

随便点一个，就会溢出屏幕，回不来了，只能刷新页面。。

<img width="765" alt="image" src="https://user-images.githubusercontent.com/26807649/194810147-f6a90dc6-3af6-4e20-86a3-8598df2aa39c.png">

**Comment by likaia** [comment]
我今晚处理下

**Comment by iZaiZaiA** [comment]
> 我今晚处理下

好的，谢谢大佬

**Comment by iZaiZaiA** [comment]
> 我今晚处理下

还有个问题，WebRtc 模式截图时，拉伸了。

原本的
<img width="2208" alt="image" src="https://user-images.githubusercontent.com/26807649/194836139-de7237d9-c6bf-41ff-b2a4-370e64f890aa.png">

WebRtc 模式截图

<img width="2292" alt="image" src="https://user-images.githubusercontent.com/26807649/194836206-c02a5b1c-5d7a-4fb0-a40c-a02e74bfc2cd.png">

拉伸，变形了

**Comment by likaia** [comment]
> > 我今晚处理下
> 
> 还有个问题，WebRtc 模式截图时，拉伸了。
> 
> 原本的 <img alt="image" width="2000" src="https://user-images.githubusercontent.com/26807649/194836139-de7237d9-c6bf-41ff-b2a4-370e64f890aa.png">
> 
> WebRtc 模式截图
> 
> <img alt="image" width="2000" src="https://user-images.githubusercontent.com/26807649/194836206-c02a5b1c-5d7a-4fb0-a40c-a02e74bfc2cd.png">
> 
> 拉伸，变形了

这个变形问题，我看下怎么修复吧

**Comment by iZaiZaiA** [comment]
> > > OK，我空闲了处理下这个问题。
> > 
> > 
> > 最新 1.7.4 版本，全屏截图时，溢出的问题还是存在。当你点击工具栏其中一个功能后，就会溢出，滚动也没用。
> > <img alt="image" width="553" src="https://user-images.githubusercontent.com/26807649/194810370-b0a15eb6-5796-48d3-93c0-f1c3194b76c1.png">
> > 随便点一个，就会溢出屏幕，回不来了，只能刷新页面。。
> > <img alt="image" width="765" src="https://user-images.githubusercontent.com/26807649/194810147-f6a90dc6-3af6-4e20-86a3-8598df2aa39c.png">
> 
> 这个问题修复了

好的，谢谢
