### ISSUE TITLE
用矩形绘制的时候蒙层会消失，多次绘制矩形，之前绘制的矩形会消失

### ISSUE THREAD

**Issue by zyx20100911** [likaia/js-screen-shot#64]
![image](https://user-images.githubusercontent.com/65153966/183624247-15c04e5d-b340-4459-b7b6-e00cc217abe4.png)
用矩形绘制的时候蒙层会消失，多次绘制矩形，之前绘制的矩形会消失咋办呀

**Comment by likaia** [comment]
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/35120858/183672461-a51bfa8a-9cc2-4cf3-a6bd-5c90b39a2e9c.png">
我试了下，没问题

**Comment by zyx20100911** [comment]
https://user-images.githubusercontent.com/65153966/183790725-65b38597-ebf4-4fac-a218-490a2d4d9b1e.mp4

感谢回复！
我克隆项目打包在dist/demo.html里使用还是会出现绘制矩形失去蒙层的情况
 "version": "1.7.2"
demo.html
![image](https://user-images.githubusercontent.com/65153966/183791069-296f0493-2eee-4253-a4be-6799332951e4.png)

**Comment by zyx20100911** [comment]
我用edge浏览器是没问题的，用谷歌浏览器会像视频那样矩形失去蒙层
Chrome
版本 104.0.5112.81（正式版本） （64 位）

**Comment by likaia** [comment]
我也是这个版本的谷歌浏览器，没出现你所说的问题。

<img width="894" alt="image" src="https://user-images.githubusercontent.com/35120858/184517382-38b6ad94-2cf7-4383-b1a3-ae13fab3572f.png">

**Comment by cc128** [comment]
> ![图片](https://user-images.githubusercontent.com/65153966/183624247-15c04e5d-b340-4459-b7b6-e00cc217abe4.png) 用矩形绘制的时候蒙层会消失，多次绘制矩形，之前绘制的矩形会消失咋办呀
兄弟，我也碰到了和你描述一模一样的问题，有解决办法了吗

**Comment by likaia** [comment]
https://user-images.githubusercontent.com/35120858/185513856-32ac90a8-bd2a-400c-a660-448528215005.mov

我这个没问题呀，我的谷歌浏览器版本：

<img width="765" alt="image" src="https://user-images.githubusercontent.com/35120858/185513919-b5284c23-fdbc-4e2b-b7fc-d6ac3fdc86a7.png">

**Comment by likaia** [comment]
修复了，插件更新到1.7.3版本即可。

**Comment by likaia** [comment]
> > ![图片](https://user-images.githubusercontent.com/65153966/183624247-15c04e5d-b340-4459-b7b6-e00cc217abe4.png) 用矩形绘制的时候蒙层会消失，多次绘制矩形，之前绘制的矩形会消失咋办呀
> > 兄弟，我也碰到了和你描述一模一样的问题，有解决办法了吗

已修复，插件更新至1.7.3版本即可。

**Comment by likaia** [comment]
> ![image](https://user-images.githubusercontent.com/65153966/183624247-15c04e5d-b340-4459-b7b6-e00cc217abe4.png) 用矩形绘制的时候蒙层会消失，多次绘制矩形，之前绘制的矩形会消失咋办呀

已修复，插件更新至1.7.3版本即可。
