### ISSUE TITLE
能否增加一个关闭裁剪框的公共方法

### ISSUE THREAD

**Issue by nitenzhao** [likaia/js-screen-shot#65]
现在关闭裁剪框只能是通过点击工具栏按钮来完成，但在某些场景下需要外部调用方法来关闭

**Comment by likaia** [comment]
暂时没时间搞，目前是有一个默认的esc快捷键来关闭裁剪框的

**Comment by moyongqing** [comment]
同步，现在electron这边点击保存后没有相应的回调方法，导致页面没办法关闭

**Comment by likaia** [comment]
> 现在关闭裁剪框只能是通过点击工具栏按钮来完成，但在某些场景下需要外部调用方法来关闭

增加了一个destroyComponents方法，更新到1.8.2版本即可。

**Comment by likaia** [comment]
> 同步，现在electron这边点击保存后没有相应的回调方法，导致页面没办法关闭

增加了一个destroyComponents方法，更新到1.8.2版本即可。
