### ISSUE TITLE
触发截图后2-4秒才能加载到mask层

### ISSUE THREAD

**Issue by hhf-ggt** [likaia/js-screen-shot#66]
htmlToCanvas比较慢、只能用webRtc么？有没有什么优化手段呢！大佬

**Comment by likaia** [comment]
这个暂时没办法，将dom转为canvas目前做的最好的就是html2canvas了

**Comment by kcker** [comment]
能不能触发截图就先出现 mask，然后加个 loading 效果，不然用户可能以为卡死了

**Comment by likaia** [comment]
> 能不能触发截图就先出现 mask，然后加个 loading 效果，不然用户可能以为卡死了

有提供triggerCallback，可以搭配来在项目里提供loading效果，具体看文档： https://www.kaisir.cn/js-screen-shot/docs/config/#5zon5bqu5zue6lcd
