### ISSUE TITLE
当把浏览器进行缩放之后，截屏的区域显示有问题

### ISSUE THREAD

**Issue by qtanran** [likaia/js-screen-shot#67]
当把浏览器进行缩放之后，截屏的区域显示就会出现问题
![image](https://user-images.githubusercontent.com/48440870/185891543-5f3717b1-9cac-4d53-9310-a3343ad9a890.png)
![image](https://user-images.githubusercontent.com/48440870/185891997-60c1f525-da67-4897-8840-950ac361e0c8.png)

**Comment by likaia** [comment]
因为它抓取的是当前窗口大小的内容，你所放后自然就会出问题了
