### ISSUE TITLE
可以增加一个点击分享按钮后的回调方法吗？

### ISSUE THREAD

**Issue by cc128** [likaia/js-screen-shot#68]
![M@QRLNURQ5(CIEQND4 Q}XP](https://user-images.githubusercontent.com/22003448/187112823-310c4196-38d4-4063-9f9d-21d5333836c8.png)

**Comment by likaia** [comment]
我晚点弄一下，暂时没时间

**Comment by likaia** [comment]
> ![M@QRLNURQ5(CIEQND4 Q}XP](https://user-images.githubusercontent.com/22003448/187112823-310c4196-38d4-4063-9f9d-21d5333836c8.png)

增加了，插件更新到1.7.7版本，传入triggerCallback参数即可
