### ISSUE TITLE
webRtc截屏window.screen宽高问题

### ISSUE THREAD

**Issue by bigbigEden** [likaia/js-screen-shot#71]
因为rtc截屏默认使用的window.screen（全屏截），导致窗口缩小，或者分享整个窗口再去截屏的时候渲染的图片宽高会不对（因为默认使用的window.screen)

可能需要修改成videoContainer实际的videoHeight和videoWidth

**Comment by bigbigEden** [comment]
还有一些别的问题，直接除暴的设置video可能还不太好，汇总后再确认下

**Comment by Curacao-lb** [comment]
我也遇到这个问题，截不全
