### ISSUE TITLE
edge浏览器截图空白

### ISSUE THREAD

**Issue by gunbarrelhandsomeman** [likaia/js-screen-shot#73]
edge浏览器，选择整个屏幕时，截图出现空白图片。求指导

**Comment by likaia** [comment]
这个兼容性可能不太好，谷歌浏览器应该没问题吧

**Comment by gunbarrelhandsomeman** [comment]
我看了一下，选择屏幕点击分享后摁住推拽并没有屏幕背景截图，是抓取屏幕那边出了问题吗？

**Comment by likaia** [comment]
> 我看了一下，选择屏幕点击分享后摁住推拽并没有屏幕背景截图，是抓取屏幕那边出了问题吗？

你试一下插件的最新版本

**Comment by gunbarrelhandsomeman** [comment]
ok了，大概看了一下，之前的问题是因为宽高不是满屏导致的吗？晚上回去认真拜读一下，感谢大佬的付出。

**Comment by likaia** [comment]
> ok了，大概看了一下，之前的问题是因为宽高不是满屏导致的吗？晚上回去认真拜读一下，感谢大佬的付出。

对的，因为不是满屏引发的
