### ISSUE TITLE
引用的antd组件，但是没有边框样式，截图出来会有边框样式

### ISSUE THREAD

**Issue by clgGit** [likaia/js-screen-shot#79]
截图：![image](https://user-images.githubusercontent.com/48577957/196645645-d22596ed-9c1a-4091-b050-6129029ca6d5.png)
原图：![image](https://user-images.githubusercontent.com/48577957/196646845-294668d0-9fcb-4042-b77a-d84b13af5e33.png)

**Comment by likaia** [comment]
webrtc模式会完美些，html2canvas没那么完美
