### ISSUE TITLE
截图时会把原有的图片隐藏, 我用的element-ui库

### ISSUE THREAD

**Issue by MuQinS** [likaia/js-screen-shot#8]
原页面:![image](https://user-images.githubusercontent.com/48786616/118742634-5fa7ef80-b883-11eb-8c78-581491ee6d77.png)
截图时的页面:
![image](https://user-images.githubusercontent.com/48786616/118742913-e6f56300-b883-11eb-8381-738d0a730f53.png)

**Comment by likaia** [comment]
图片跨域了

**Comment by MuQinS** [comment]
请问可以配置允许跨域吗?

**Comment by likaia** [comment]
用webrtc模式

**Comment by MuQinS** [comment]
谢谢解答
