### ISSUE TITLE
修改裁剪框大小后裁剪框无法正常移动

### ISSUE THREAD

**Issue by yand9807** [likaia/js-screen-shot#80]
您好，我在使用时发现了个问题
1.第一次设定好裁剪框的大小：{x:0,y:0,w:800,h:800}，然后进行截图，一切正常
2.关闭截图后修改裁剪框的大小为：{x:0,y:0,w:900,h:800}，然后再次进行截图
3.此时截图框用鼠标拖拽进行移动，截图框可上下拖动，无法左右拖动，当水平方向拖动超过一定距离时整个截图框会直接跳到屏幕的一侧
4。此时使用鼠标调整一下截图框的大小然后再拖动即恢复正常

**Comment by likaia** [comment]
我测了下，没有发现这个问题。你第二次修改裁剪框大小参数后，有没有重新实例化插件呢？
