### ISSUE TITLE
chrome浏览器在开启书签栏时工具栏会被遮住

### ISSUE THREAD

**Issue by yand9807** [likaia/js-screen-shot#81]
![image](https://user-images.githubusercontent.com/53848372/202338035-b9aa23f9-421e-4792-ac93-8e9ed5488e8c.png)

**Comment by likaia** [comment]
<img width="944" alt="image" src="https://user-images.githubusercontent.com/35120858/204120788-8d35b0c4-2e4e-46c3-a095-ac247aa2b4a6.png">
我测了下，没有这个问题
