### ISSUE TITLE
webrtc模式canvas画布中的屏幕是变形的，宽高比例变了

### ISSUE THREAD

**Issue by tanglinhai** [likaia/js-screen-shot#83]
webrtc模式canvas画布中的屏幕是变形的，宽高比例变了，能保持宽高比例吗？多余部分留白

**Comment by likaia** [comment]
默认应该不会吧？他拿的是当前tab页的内容

**Comment by tanglinhai** [comment]
![image](https://user-images.githubusercontent.com/14047733/209768469-04dc5fb9-df33-4d4d-907b-bef813e608dc.png)

**Comment by tanglinhai** [comment]
![222222222](https://user-images.githubusercontent.com/14047733/209768885-34402839-2f17-48c0-99be-b53d9b944512.png)
分享这个命令行窗口，截图的canvas展示成这样了

**Comment by tanglinhai** [comment]
就是图片的尺寸高度和宽度拉伸没有按比例来，导致图片变形了，这个能解决吗？这个比较重要的问题。

还有一个问题估计不太好解决，就是点击分享后，被分享的应用会置顶到当前的截图操作界面。

**Comment by sj216** [comment]
您好，请问下1.8.0版本下，使用html2canvas模式下截图，原网页中所有jpg，svg图片都白屏了，这个怎么解决呐

**Comment by tanglinhai** [comment]
![3333333333](https://user-images.githubusercontent.com/14047733/209778909-e18c6f41-8d21-41bd-a447-b7accc69d34c.png)
我已经找到问题了，这样就解决了。

**Comment by tanglinhai** [comment]
![4444444444](https://user-images.githubusercontent.com/14047733/209779414-56dddf56-9f3c-4300-9e74-420b9836f20a.png)
这就是改完后的效果

**Comment by tanglinhai** [comment]
@likaia 这个我上面的代码只是做了自适应的方式，你可以改成根据高度自适应或者根据宽度自适应，甚至可以做成可配置项，这个问题解决了
还有一个问题：点击分享后，被分享的应用会置顶到当前的截图操作界面。 这个设计的浏览器原生弹窗，这个有时间解决吗？不要让第三方应用置顶到界面顶部

**Comment by likaia** [comment]
> @likaia 这个我上面的代码只是做了自适应的方式，你可以改成根据高度自适应或者根据宽度自适应，甚至可以做成可配置项，这个问题解决了 还有一个问题：点击分享后，被分享的应用会置顶到当前的截图操作界面。 这个设计的浏览器原生弹窗，这个有时间解决吗？不要让第三方应用置顶到界面顶部

ok，修复了，1.8.1版本
