### ISSUE TITLE
html2canvas能否升级为最新版本或者较新版本

### ISSUE THREAD

**Issue by Curacao-lb** [likaia/js-screen-shot#85]
新版本html2canvas可支持截图 video 标签，能否兼容升级一下

**Comment by likaia** [comment]
> 新版本html2canvas可支持截图 video 标签，能否兼容升级一下

可以的，我升级下。

**Comment by likaia** [comment]
> 新版本html2canvas可支持截图 video 标签，能否兼容升级一下

升级了，插件版本更至最新即可。
