### ISSUE TITLE
建议更改下设置canvas大小的方式

### ISSUE THREAD

**Issue by Vanisper** [likaia/js-screen-shot#88]
![Snipaste_2023-02-10_20-55-39](https://user-images.githubusercontent.com/55046983/218097750-3fba7e52-af54-4c26-8c9e-1f851acaa389.png)

`window.innerWidth`这种方式会有四舍五入的问题
`window.getComputedStyle(document.body).width`能准确获取dom的大小
但是它返回的是一个字符串，例如：`123px`
所以做下处理
`+window.getComputedStyle(document.body).width.split("px")[0]`
这就是一个number了
（加号的作用是，快速将字符串转数字）

**Comment by likaia** [comment]
OK，感谢你的建议，已经更改了，将插件更新至1.8.4版本即可。

**Comment by Vanisper** [comment]
大佬辛苦了






                       
原始邮件
                       
                     

发件人："likai"< ***@***.*** &gt;;

发件时间：2023/2/13 22:23

收件人："likaia/js-screen-shot"< ***@***.*** &gt;;

抄送人："Vanisper"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [likaia/js-screen-shot] 建议更改下设置canvas大小的方式 (Issue #88)




 
OK，感谢你的建议，已经更改了，将插件更新至1.8.4版本即可。
