### ISSUE TITLE
截图工具栏保存后回调么

### ISSUE THREAD

**Issue by syx496602504** [likaia/js-screen-shot#89]

**Comment by Vanisper** [comment]
``` ts
const option = {
        level: 999,
        completeCallback: (e: string) =>{
        // doSomething
        // e是图片base64字符串
        }
}
new ScreenShot(option);
```

**Comment by likaia** [comment]
？

**Comment by syx496602504** [comment]
工具栏下载按钮的回调

![1677562809438](https://user-images.githubusercontent.com/44331245/221764056-8bd4a85a-1526-4628-b898-8987d16c3812.png)

**Comment by likaia** [comment]
> 工具栏下载按钮的回调
> 
> ![1677562809438](https://user-images.githubusercontent.com/44331245/221764056-8bd4a85a-1526-4628-b898-8987d16c3812.png)

不是的，这个回调指的是点了对号之后的

**Comment by syx496602504** [comment]
对号之后的回调看到文档里写了，是想请问下有没有下载这个按钮的回调

**Comment by likaia** [comment]
> 对号之后的回调看到文档里写了，是想请问下有没有下载这个按钮的回调

下载回调没有提供

**Comment by syx496602504** [comment]
好的，谢谢~

**Comment by likaia** [comment]
> 好的，谢谢~

如果需要的话，我晚上加一下。

**Comment by syx496602504** [comment]
不用麻烦了，多谢
