### ISSUE TITLE
我运行出来是黑屏，没有显示截图，是还需要其他配置吗？最新版chrome

### ISSUE THREAD

**Issue by MoonShadowLau** [likaia/js-screen-shot#9]
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Document</title>
	</head>
	<body>
		<div id="" style="width: 100%;height: 100px;background-color: #009F95;">
		</div>
		<script src="./screenShotPlugin.umd.js"></script>
		<script type="text/javascript">
			window.onload = ()=> {new screenShotPlugin(); }
		</script>
	</body>
</html>

**Comment by likaia** [comment]
你需要拖拽生成选取才行呀

**Comment by MoonShadowLau** [comment]
搞清楚了，3q

**Comment by xiang0308** [comment]
> 你需要拖拽生成选区才行呀

能默认给个全屏选区吗？
