### ISSUE TITLE
求真

### ISSUE THREAD

**Issue by wolfcdd** [likaia/js-screen-shot#91]
从这过来的
![21e69b688c90ff5b61c66d137207001](https://user-images.githubusercontent.com/5728354/222345873-a33e1db7-b0d5-4d6e-bbfb-01849f69f5b0.jpg)

**Comment by kingofzihua** [comment]
这么卑微吗？

**Comment by chenjiajing23** [comment]
69

**Comment by likeyoukang** [comment]
我也是从这过来的

**Comment by ljlstc123456** [comment]
看来 这个帖子是故意有人放出来的

**Comment by lxfu1** [comment]
感觉是引流啊

**Comment by likaia** [comment]
对，这个是我，我当时只是发到自己群里跟他们吐槽下找工作太难了，一个20人的公司就收到上百份简历，没想到一下子传播开了。

issue区域是讨论跟项目相关的，不讨论这些东西哈，这个issue我删掉了哈。
