### ISSUE TITLE
兄弟网上看个帖子，请问这是你吗？ 是真的吗？

### ISSUE THREAD

**Issue by ljlstc123456** [likaia/js-screen-shot#92]
![image](https://user-images.githubusercontent.com/3302065/222390591-c77f5d09-773f-4811-819a-7e3f4b261b9c.png)

**Comment by lxfu1** [comment]
应该是真的，我也看了！

**Comment by likaia** [comment]
对，这个是我，我当时只是发到自己群里跟他们吐槽下找工作太难了，一个20人的公司就收到上百份简历，没想到一下子传播开了。

issue区域是讨论跟项目相关的，不讨论这些东西哈，这个issue我删掉了哈。
