### ISSUE TITLE
截图工具栏超出屏幕，显示不全

### ISSUE THREAD

**Issue by syx496602504** [likaia/js-screen-shot#93]
![1678236826414](https://user-images.githubusercontent.com/44331245/223590952-6ad25280-83dd-4a9e-a224-d65a26699bb4.png)

靠左或右截小图

**Comment by likaia** [comment]
> ![1678236826414](https://user-images.githubusercontent.com/44331245/223590952-6ad25280-83dd-4a9e-a224-d65a26699bb4.png)
> 
> 靠左或右截小图

<img width="908" alt="image" src="https://user-images.githubusercontent.com/35120858/226111113-343bed29-df20-4090-b587-f874f5494d0e.png">
我试了下正常的

**Comment by syx496602504** [comment]
麻烦你截的区域小一点再试一下，例如截一个200宽的，截图框比下面工具栏长度短，靠左或右截能复现

**Comment by likaia** [comment]
> 麻烦你截的区域小一点再试一下，例如截一个200宽的，截图框比下面工具栏长度短，靠左或右截能复现

发现这个问题了，我处理下

**Comment by likaia** [comment]
> 麻烦你截的区域小一点再试一下，例如截一个200宽的，截图框比下面工具栏长度短，靠左或右截能复现

已修复，将插件更新到最新版本即可。

**Comment by syx496602504** [comment]
```javascript
import ScreenShot from 'js-web-screen-shot';

  new ScreenShot({
      completeCallback: base64 => {
        console.log('截图完成', base64);
      },
      closeCallback: () => {
        console.log('截图窗口关闭');
      },
    });
```

升级依赖包运行报错
![image](https://user-images.githubusercontent.com/44331245/227872632-1efb02f1-68e4-4393-aa81-7ae03effdc6f.png)
