### ISSUE TITLE
非webRtc，长页面内，截图区域位置不对

### ISSUE THREAD

**Issue by Clovis0070** [likaia/js-screen-shot#94]
![image](https://user-images.githubusercontent.com/25895886/224912308-7abd172c-9e6c-4773-922f-1ffe7434b229.png)
页面可以滚动，向下滚动一些，然后截图，发现截图操作区域不会到页面顶部。

此时点击开始截图，发现不在操作区域的内容被复制到了操作区域内，出现视觉上的异常
![image](https://user-images.githubusercontent.com/25895886/224912640-7ce27a1b-e198-43ea-b2f3-97c21611b692.png)

尝试设置 position 参数，不生效。

**Comment by Clovis0070** [comment]
#93 尝试设置 position 参数不生效，是数值判断有问题，数值设置为 0 时不生效

**Comment by Clovis0070** [comment]
尝试设置 position 参数不生效，是数值判断有问题，数值设置为 0 时不生效

**Comment by Clovis0070** [comment]
尝试设置 position 参数不生效，是数值判断有问题，数值设置为 0 时不生效

**Comment by likaia** [comment]
> 

怎么说？数值为0？我没理解你所说的

**Comment by likaia** [comment]
> 尝试设置 position 参数不生效，是数值判断有问题，数值设置为 0 时不生效

怎么说？数值为0？我没理解你所说的
