### ISSUE TITLE
左上角出现一个奇怪的字符

### ISSUE THREAD

**Issue by huzexing** [likaia/js-screen-shot#96]
当前网页截图从左上滑到右下截图时，左上角会出现一个奇怪的字符

**Comment by likaia** [comment]
什么字符？我这里没出现

**Comment by huzexing** [comment]
是在使用非webRtc下截图会有，我把图片发你邮件看看。

**Comment by huzexing** [comment]
风雨亭、邂逅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "likaia/js-screen-shot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月18日(星期六) 晚上9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [likaia/js-screen-shot] 左上角出现一个奇怪的字符 (Issue #96)





 
什么字符？我这里没出现

**Comment by likaia** [comment]
> 是在使用非webRtc下截图会有，我把图片发你邮件看看。

会不会是你的html写的不规范呢？可以提供一份demo代码吗？

**Comment by huzexing** [comment]
可以的，稍后邮箱发给你这份代码

**Comment by huzexing** [comment]
你好，这是我写demo的代码，需要下载依赖启动服务




风雨亭、邂逅
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "likaia/js-screen-shot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 晚上9:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [likaia/js-screen-shot] 左上角出现一个奇怪的字符 (Issue #96)





  
是在使用非webRtc下截图会有，我把图片发你邮件看看。
  
会不会是你的html写的不规范呢？可以提供一份demo代码吗？

**Comment by likaia** [comment]
> 你好，这是我写demo的代码，需要下载依赖启动服务 风雨亭、邂逅 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "likaia/js-screen-shot" ***@***.***&gt;; 发送时间:&nbsp;2023年3月24日(星期五) 晚上9:33 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [likaia/js-screen-shot] 左上角出现一个奇怪的字符 (Issue #96) 是在使用非webRtc下截图会有，我把图片发你邮件看看。 会不会是你的html写的不规范呢？可以提供一份demo代码吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

？你有法代码吗？我没看到

**Comment by likaia** [comment]
> 你好，这是我写demo的代码，需要下载依赖启动服务 风雨亭、邂逅 ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "likaia/js-screen-shot" ***@***.***&gt;; 发送时间:&nbsp;2023年3月24日(星期五) 晚上9:33 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [likaia/js-screen-shot] 左上角出现一个奇怪的字符 (Issue #96) 是在使用非webRtc下截图会有，我把图片发你邮件看看。 会不会是你的html写的不规范呢？可以提供一份demo代码吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

？你有法代码吗？我没看到
