### ISSUE TITLE
只截可视页面怎么设置？

### ISSUE THREAD

**Issue by PRHyzzza** [likaia/js-screen-shot#98]
页面过长会把整个body截一下，导致页面比例怪异

**Comment by likaia** [comment]
webrtc模式是可以的，html2canvas模式暂时不行

**Comment by allenzoe** [comment]
修改src/main.ts文件下面html2canvas截屏函数 ，可以实现可视页面区域截图效果，如下图所示
![image](https://github.com/likaia/js-screen-shot/assets/48663314/d4f07fa2-28a3-466b-b582-376ffa8cfdba)
