### ISSUE TITLE
引用报错

### ISSUE THREAD

**Issue by sz-phg** [likaia/js-screen-shot#99]
我在今天更新依赖文件后，发现js-screen-shot的引用上报错，点击引用路径时会找不到文件

**Comment by likaia** [comment]
什么报错，方便提供个截图吗？

**Comment by likaia** [comment]
😂抱歉，我的锅package.json中的声明文件忘记改了，已修复。更新到1.8.8即可

**Comment by sz-phg** [comment]
麻烦你了
